/*<?xml version="1.0" encoding="ISO-8859-1"?>
<source name="hlprodsp.c">
<pvcs>
  <!-- these tags are filled out by version control system during check in -->
  <revision>$Revision: 1.10 $</revision>
  <archiveTimeStamp>$Date: 2008/11/06 17:56:28 $</archiveTimeStamp>
  <pvcsUser>$Author: jru $</pvcsUser>
</pvcs>
<comments>
  <fileName>hlprodsp.c</fileName>
  <creationDate></creationDate>

  <rights></rights>
  <author>GEN_HLC.EXE</author>

  <description>
    <fr>Interface pour les CALL entre Progress et les routines C</fr>
    <nl>Interface voor de Progress CALL's naar C routines</nl></description>
  <history></history>
  <comment>
//***************************************************
//* FILE   : HLPRODSP.C                             *
//*                                                 *
//*   Automatically generated by GEN_HLC.EXE        *
//***************************************************</comment>
</comments>
<header>*/

#define FUNCTEST(nam, rout)  \
    if (strcmp(nam, pfunnam) == 0) \
        return rout(argc,argv);

/***************************************************/
/* PROGRAM: PRODSP                                 */
/*                                                 */
/*   This is the interface to all C routines that  */
/*   PROGRESS has associated 'call' statements to. */
/***************************************************/
/*<includes>*/
#include <stdio.h>
/*</includes>*/

/*<prototypes>*/
extern int doserr();
/*</prototypes>
</header>

<body>*/

/*<function id="PRODSP">
<heading>
  <description>
    <fr>Interface pour les CALL entre Progress et les routines C</fr>
    <nl>Interface voor de Progress CALL's naar C routines</nl></description>
<parameters>
  <parameter>
    <datatype>char*</datatype>
      <name>pfunnam</name>
      <description>
        <fr>nom de la fonction à appeler</fr>
        <nl>naam van de op te roepen functie</nl></description></parameter>
  <parameter>
    <datatype>int</datatype>
      <name>argc</name>
      <description>
        <fr>pas utilisé</fr>
        <nl>ongebruikt</nl></description></parameter>
  <parameter>
    <datatype>char*</datatype>
      <name>argv[1]</name>
        <description>
          <fr>pas utilisé</fr>
          <nl>ongebruikt</nl></description></parameter>
</parameters>
</heading>
<code>*/
long
PRODSP (pfunnam, argc, argv)

     char* pfunnam;    /* Name of function to call */
     int     argc;
     char   *argv[];
{
    char cString[ 76];

    FUNCTEST ("C_ATTRIB", c_attrib);
    FUNCTEST ("C_COPY", c_copy);
    FUNCTEST ("C_DEL", c_del);
    FUNCTEST ("C_DIR", c_dir);
    FUNCTEST ("C_MKDIR", c_mkdir);
    FUNCTEST ("C_EXEC", c_exec);
    FUNCTEST ("C_LABEL", c_label);
    FUNCTEST ("C_PRINT", c_print);
    FUNCTEST ("C_PRSTAT", c_prstat);
    FUNCTEST ("C_PRTYPE", c_prtype);
    FUNCTEST ("C_GETENV", c_getenv);
    FUNCTEST ("C_TSTDSK", c_tstdsk);
    FUNCTEST ("C_TSTFN", c_tstfn);

    FUNCTEST ("C_CHECKINT", c_checkint);

    FUNCTEST ("QUOT", quot);
    FUNCTEST ("QUOTD", quotd);

    FUNCTEST ("CRYPKEYS", crypkeys);
    FUNCTEST ("CRYPSK", crypsk);
    FUNCTEST ("CRYPFILE", crypfile);
    FUNCTEST ("CRYPBINF", crypbinf);
    FUNCTEST ("CRYPMAC", crypmac);
    FUNCTEST ("READMAC", readmac);
    FUNCTEST ("CRYPENC", crypenc);
    FUNCTEST ("CRYPDEC", crypdec);
    FUNCTEST ("CRYPINIT", crypinit);
    FUNCTEST ("CRYPSTOP", crypstop);
    FUNCTEST ("C_KEYGEN", c_keygen);
    FUNCTEST ("CRYPAUT", crypaut);

    FUNCTEST ("DIGEST", digest);
    FUNCTEST ("ADDTOLOG", addtolog);
    FUNCTEST ("MEMAVAIL", memavail);
    FUNCTEST ("C_FSIZE", c_fsize);
    FUNCTEST ("C_DFREE", c_dfree);
    FUNCTEST ("C_TOUCH", c_touch);

    FUNCTEST ("RAWRITE", rawrite);
    FUNCTEST ("MK_IMAGE", mk_image);
    FUNCTEST ("GET_FROM_IMAGE", get_from_image);

    sprintf( "Hlprodsp.c : call to undefined c-function [%s].",
       pfunnam);
    promsgd( cString);
    return 1;
}
/*</code>
</function>
</body>
</source>*/