/*******************************************************************/
/* DEBUT DU MODULE ERREUR.C -- HEADER                              */
/*******************************************************************/

void Wait_Time(int Sec);
int error_win(int numerror);
/* START CONFIDENTIAL */
int handler(unsigned errval,unsigned di,unsigned far *devhdr);
void hardresume(int retval);
void hardretn(int result);
/* END CONFIDENTIAL */

/*******************************************************************/
/* FIN DU MODULE ERREUR.C -- HEADER                                */
/*******************************************************************/
