/*<?xml version="1.0" encoding="ISO-8859-1"?>
<source name="aes.h">
<pvcs><!-- these tags are filled out by pvcs during check in -->
<workFile>$Workfile:   AES.h  $</workFile>
<revision>$Revision: 1.1 $</revision>
<workFileTimeStamp>$Modtime:   Mar 19 2003 09:21:10  $</workFileTimeStamp>
<archive>$Archive:   C:/PVCS VM/v6.8.00/DIGIVOTE/Archives/Digivote/Prg/AES/AES.h-arc  $</archive>
<archiveTimeStamp>$Date: 2005/02/07 11:32:01 $</archiveTimeStamp>
<pvcsUser>$Author: avanderhoudelingen $</pvcsUser>
</pvcs>
<comments>
  <fileName>AES.H</fileName>
  <creationDate>Sept 2001</creationDate>
  <rights></rights>
  <author>AVN</author>
  <description>
    <fr>AES.cpp header file</fr>
    <nl>AES.cpp header file</nl></description>
  <history></history>
  <comment></comment>
</comments>*/
//===============================================================================
#ifndef _AES_H_                     // Avoids multiple includes of this file
   #define _AES_H_

   #include "..\aes\fullspec.h"
#endif
