.head 0 +  Application Description: SQLWindows version 5.0 starter application
.data CLASSPROPSSIZE
0000: 3800
.enddata
.data CLASSPROPS
0000: 4170705061746800 0000004170705061 74684C656E000400 0000000000557365
0020: 476C6F62616C5061 7468000400010000 0000000000000000
.enddata
.head 1 -  Outline Version - 4.0.31
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000E60000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE9FFFFFF000000 0000000000360200 00B9020000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600020003001B00 02000000C5000000 0000F82874180500 1D00FFFF4D61696E
0020: 002400000002008D 012602CA01732130 1200004200FFFF64 6C674D7474426566
0040: 4575726F00
.enddata
.data VIEWSIZE
0000: 4500
.enddata
.head 3 -  Left: -0.013"
.head 3 -  Top: 0.0"
.head 3 -  Width:  8.013"
.head 3 -  Height: 4.969"
.head 2 +  Options Box Location
.data VIEWINFO
0000: D4180909B80B1A00
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 4.15"
.head 3 -  Top: 1.885"
.head 3 -  Width:  3.8"
.head 3 -  Height: 2.073"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: 0.338"
.head 3 -  Top: 0.052"
.head 3 -  Width:  5.063"
.head 3 -  Height: 2.719"
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 10.225"
.head 3 -  Top: 1.469"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? Yes
.head 2 -  Enable Runtime Checks Of External References? Yes
.head 2 -  Use Release 4.0 Scope Rules? No
.head 1 +  Libraries
.head 2 -  File Include: baseclas.apl
.head 2 -  ! File Include: PGLOBVAR.apl
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: MS Sans Serif
.head 4 -  Font Size: 8
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: MS Sans Serif
.head 4 -  Font Size: 8
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: MS Sans Serif
.head 4 -  Font Size: 8
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Top Level Table Window
.head 4 -  Font Name: MS Sans Serif
.head 4 -  Font Size: 8
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Line
.head 4 -  Line Color: Use Parent
.head 3 +  Frame
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0'%'
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;'($'###000')'
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 3 -  Number: ###0
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  String: C_OPGELET				= 'Opgelet'
.head 4 -  String: C_ATTENTION			= 'Attention'
.head 4 -  String: C_FMT_EURO			= '#.##0,00'
.head 4 -  String: C_FMT_BEF				= '#.##0'
.head 4 -  ! String: cPathStesud			= 'c:\\stesud.tmp'
.head 4 -  String: __RELEASE1		= 'release'
.head 4 -  String: __RELEASE2		= 'release.'
.head 4 -  String: __0			= '0'
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 1211865023
0000: 2200000013000000 0000000000000000 020000010000000D 030000D019000000
0020: 01FE00FF03
.enddata
.head 3 -  !
.head 3 -  ! Variable indiquant si on travaille en Euro
.head 3 -  Boolean: gbEuro
.head 3 -  ! TRUE si la comptabilité est en Euro
.head 3 -  ! FALSE sinon
.head 3 -  Window Handle: gwhWndEuro
.head 3 -  Boolean: gbVisualisationPieceInterne
.head 3 -  String: gsAnneeBudgetaire
.head 2 +  Internal Functions
.head 3 +  Function: PalNumberRnd
.head 4 -  Description: Arrondi un nombre à la xième décimale
.head 4 +  Returns
.head 5 -  Number:
.head 4 +  Parameters
.head 5 -  Number: pnNbr
.head 5 -  Number: pnDec
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: nTmp
.head 5 -  Number: nExp
.head 4 +  Actions
.head 5 -  Set nTmp = pnNbr
.head 5 -  Set nExp = SalNumberPower( 10, pnDec )
.head 5 -  Set nTmp = nTmp * nExp
.head 5 -  Set nTmp = SalNumberRound( nTmp )
.head 5 -  Set nTmp = nTmp / nExp
.head 5 -  Return nTmp
.head 3 +  Function: PalMttSubstitute
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  String: ps
.head 4 -  Static Variables
.head 4 -  Local variables
.head 4 +  Actions
.head 5 -  Return VisStrSubstitute( ps, '.', ',' )
.head 3 +  Function: PalMttSubstituteEn
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  String: ps
.head 4 -  Static Variables
.head 4 -  Local variables
.head 4 +  Actions
.head 5 -  Return VisStrSubstitute( ps, ',', '.' )
.head 3 +  Function: FP
.head 4 -  Description: Retourne la partie fractionnaire d'un nombre
.head 4 +  Returns
.head 5 -  Number:
.head 4 +  Parameters
.head 5 -  Number: pnValeur
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: n
.head 4 +  Actions
.head 5 -  Set n = SalNumberMod( pnValeur, 1 ) 
.head 5 -  Return n
.head 3 +  Function: IP
.head 4 -  Description: Retourne la partie entière d'un nombre
.head 4 +  Returns
.head 5 -  Number:
.head 4 +  Parameters
.head 5 -  Number: pnValeur
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: n
.head 4 +  Actions
.head 5 -  Set n = FP( pnValeur )
.head 5 -  Return pnValeur - n
.head 3 +  Function: ArrondiEuro
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Number:
.head 4 +  Parameters
.head 5 -  Number: pnValeur
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: n
.head 4 +  Actions
.head 5 -  Set n = IP( pnValeur * 100 )
.head 5 -  Set n = n / 100
.head 5 -  Return n
.head 3 +  Function: ArrondiBEF
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Number:
.head 4 +  Parameters
.head 5 -  Number: pnValeur
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: n
.head 4 +  Actions
.head 5 -  Set n = IP( pnValeur  )
.head 5 -  Return n
.head 3 +  Function: ToBEF
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Number:
.head 4 +  Parameters
.head 5 -  Number: pnValeur
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: n
.head 4 +  Actions
.head 5 -  Set n = pnValeur * 40.3399
.head 5 -  Set n = ArrondiBEF( n + 0.5 )
.head 5 -  Return n
.head 3 +  Function: ToEuro
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Number:
.head 4 +  Parameters
.head 5 -  Number: pnValeur
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: n
.head 4 +  Actions
.head 5 -  Set n = pnValeur / 40.3399
.head 5 -  Set n = ArrondiEuro( n + 0.005 )
.head 5 -  Return n
.head 3 +  Function: ExtractFilePath
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  String: psFile
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: sRepPrgm
.head 4 +  Actions
.head 5 -  Set sRepPrgm = psFile
.head 5 +  If sRepPrgm != ''
.head 6 +  While SalStrRightX( sRepPrgm, 1 ) != '\\'
.head 7 -  Set sRepPrgm = SalStrLeftX( sRepPrgm, SalStrLength( sRepPrgm ) - 1 )
.head 6 +  If SalStrRightX( sRepPrgm, 1 ) = '\\'
.head 7 -  Set sRepPrgm = SalStrLeftX( sRepPrgm, SalStrLength( sRepPrgm ) - 1 )
.head 5 -  Return sRepPrgm
.head 3 +  Function: ExtractFileName
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  String: psFile
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: sRepPrgm
.head 5 -  Number: nPos
.head 4 +  Actions
.head 5 -  Set sRepPrgm = psFile
.head 5 +  If sRepPrgm != ''
.head 6 -  Set nPos = SalStrScan( sRepPrgm, '\\\\' )
.head 6 +  While nPos >= 0
.head 7 -  Set sRepPrgm = SalStrMidX( sRepPrgm, nPos+1,SalStrLength( sRepPrgm ) )
.head 7 -  Set nPos = SalStrScan( sRepPrgm, '\\\\' )
.head 6 -  Set nPos = SalStrScan( sRepPrgm, '.' )
.head 6 -  Set sRepPrgm = SalStrMidX( sRepPrgm, 0, nPos )
.head 5 -  Return sRepPrgm
.head 3 +  Function: ExtractFileExtension
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  String: psFile
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: sRepPrgm
.head 5 -  Number: nPos
.head 4 +  Actions
.head 5 -  Set sRepPrgm = psFile
.head 5 +  If sRepPrgm != ''
.head 6 -  Set nPos = SalStrScan( sRepPrgm, '\\\\' )
.head 6 +  While nPos >= 0
.head 7 -  Set sRepPrgm = SalStrMidX( sRepPrgm, nPos+1,SalStrLength( sRepPrgm ) )
.head 7 -  Set nPos = SalStrScan( sRepPrgm, '\\\\' )
.head 6 -  Set nPos = SalStrScan( sRepPrgm, '.' )
.head 6 -  Set sRepPrgm = SalStrMidX( sRepPrgm, nPos+1, SalStrLength( sRepPrgm ) )
.head 5 -  Return sRepPrgm
.head 3 -  ! !
.head 3 +  Function: PalGetApplParmX
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  String: psApplParm
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: lsValue
.head 4 +  Actions
.head 5 +  If PalGetApplParm( psApplParm, lsValue )
.head 6 -  Return lsValue
.head 5 +  Else
.head 6 -  Return STRING_Null
.head 3 +  Function: PalGetApplParmBX
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  String: psApplParm
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: lsValue
.head 4 +  Actions
.head 5 +  If PalGetApplParm( psApplParm, lsValue )
.head 6 -  Return SalStrScan( 'YyOo1', lsValue )  >= 0
.head 5 +  Else
.head 6 -  Return FALSE
.head 3 +  Function: PalGetApplParmNoX
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  Number: pnApplParm
.head 5 -  Number: pnLength
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: lsValue
.head 4 +  Actions
.head 5 +  If PalGetApplParm( 'PAR' || SalStrRightX( SalStrRepeatX( '0', pnLength ) || SalNumberToStrX( pnApplParm, 0 ), pnLength ), lsValue )
.head 6 -  Return lsValue
.head 5 +  Else
.head 6 -  Return STRING_Null
.head 3 +  Function: PalGetApplParmNoX4
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  Number: pnApplParm
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: lsValue
.head 4 +  Actions
.head 5 -  Return PalGetApplParmNoX( pnApplParm, 4 )
.head 3 -  !
.head 3 -  !
.head 3 +  Function: SteGetTypeOfFile
.head 4 -  Description: Retourne le type de fichier associé à une extension
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  String: psExt
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: s
.head 5 -  String: s1
.head 5 -  FunctionalVar: Reg
.head 6 -  Class: cBTRegistry
.head 4 +  Actions
.head 5 -  Call Reg.SetRootKey( HKEY_CLASSES_ROOT )
.head 5 +  If SalStrLeftX( psExt, 1 ) != '.'
.head 6 -  Set psExt = '.' || psExt
.head 5 -  Set s = 'Fichiers ' || SalStrUpperX( SalStrRightX( psExt, SalStrLength( psExt ) - 1 ) )
.head 5 +  If Reg.OpenKey( '\\' || psExt, FALSE )
.head 6 +  If Reg.ReadString( '', s1 )
.head 7 -  Call Reg.CloseKey( )
.head 7 +  If Reg.OpenKey( '\\' || s1, FALSE )
.head 8 +  If Reg.ReadString( '', s1 )
.head 9 -  Set s = s1
.head 8 -  Call Reg.CloseKey( )
.head 6 +  Else
.head 7 -  Call Reg.CloseKey( )
.head 6 -  ! Call Reg.CloseKey(  )
.head 5 -  Return s
.head 3 +  Function: SteFiltreDialogOpenSave
.head 4 -  Description: Fonction pour ajouter un filtre dans les tableaux pour les fenêtres OpenFile et SaveFile de Centura
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  Receive String: prsTab[*]
.head 5 -  Receive Number: prnNbr
.head 5 -  String: psPref
.head 5 -  String: psExt
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: s
.head 4 +  Actions
.head 5 +  If SalStrLeftX( psExt, 1 ) != '.'
.head 6 -  Set psExt = '.' || psExt
.head 5 +  If psPref = ''
.head 6 -  Set psPref = '*'
.head 5 +  If psPref || psExt = '*.*'
.head 6 +  Select Case gnLanguage
.head 7 +  Case Language_NL
.head 8 -  Set s = 'Alles'
.head 8 -  Set prsTab[ prnNbr ] = s
.head 8 -  Set prnNbr = prnNbr + 1
.head 8 -  Break
.head 7 +  Default
.head 8 -  Set s = "Tous"
.head 8 -  Set prsTab[ prnNbr ] = s
.head 8 -  Set prnNbr = prnNbr + 1
.head 6 -  Set prsTab[ prnNbr ] = psPref || psExt
.head 6 -  Set prnNbr = prnNbr + 1
.head 5 +  Else
.head 6 -  Set s = SteGetTypeOfFile( psExt )
.head 6 -  Set prsTab[ prnNbr ] = s
.head 6 -  Set prnNbr = prnNbr + 1
.head 6 -  Set prsTab[ prnNbr ] = psPref || psExt
.head 6 -  Set prnNbr = prnNbr + 1
.head 3 +  Function: PalGetTransactionName
.head 4 -  Description: Fonction retournant un nom de transaction unique
.head 4 +  Returns
.head 5 -  String:
.head 4 -  Parameters
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: ComputerName
.head 5 -  Date/Time: dt
.head 5 -  String: str
.head 4 +  Actions
.head 5 -  Call SalGetProfileString( 'Network', 'ComputerName', '', ComputerName, 'system.ini' )
.head 5 -  Set dt = SalDateCurrent(  )
.head 5 -  Set str = SalFmtFormatDateTime( dt, "yyyyMMddhhhhmmss" )
.head 5 -  Set str = ComputerName || str
.head 5 -  Return str
.head 3 -  !
.head 3 -  !
.head 3 +  Function: SoldeDroit
.head 4 -  Description: Calcul le solde d'un droit sur base de la formule définie par AL

.head 4 +  Returns
.head 5 -  Number:
.head 4 +  Parameters
.head 5 -  Sql Handle: phSql
.head 5 -  String: psAnnee
.head 5 -  String: psNoDroit
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: lnRet
.head 5 -  Number: lnSolde
.head 5 -  Number: n1
.head 5 -  Number: n2
.head 4 +  Actions
.head 5 -  Call SqlPrepareAndExecute( phSql, 
	"select	sum( mtt_ddf )
	from	lst_droit1
	where	annee = " || psAnnee || "
	and	no_piece = '" || psNoDroit || "'
	into	:lnSolde" )
.head 5 +  If not SqlFetchNext( phSql, lnRet )
.head 6 -  Return 0
.head 5 -  Call SqlPrepareAndExecute( phSql, 
	'select	sum( mtt_non_val - mtt_imput )
	from	lst_droit2
	where	annee = ' || psAnnee || '
	and	no_piece = \'' || psNoDroit || '\'
	into	:n1' )
.head 5 +  If not SqlFetchNext( phSql, lnRet )
.head 6 -  Set n1 = 0
.head 5 -  Set lnSolde = lnSolde - n1
.head 5 -  Call SqlPrepareAndExecute( phSql, 
	'select	sum( mtt_paye )
	from	lst_droit4
	where	annee = ' || psAnnee || '
	and	no_piece = \'' || psNoDroit || '\'
	into	:n1' )
.head 5 +  If not SqlFetchNext( phSql, lnRet )
.head 6 -  Set n1 = 0
.head 5 -  Set lnSolde = lnSolde - n1
.head 5 -  Return lnSolde
.head 3 +  Function: GetIncNumID
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  Sql Handle: phSqlRecherche
.head 5 -  ! String: psAnnee
.head 5 -  ! String: psNum
.head 5 -  Number: pnExp
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Sql Handle: fhSqlRecherche
.head 5 -  Number: nRet
.head 5 -  Number: nVal
.head 5 -  String: sRet
.head 5 -  Number: i
.head 5 -  String: lsTable
.head 5 -  String: ssMod
.head 5 -  String: lsFmt
.head 4 +  Actions
.head 5 -  ! Call PalSqlConnectTransaction( fhSqlRecherche, GetTransactionName(  ) )
.head 5 -  ! If ssMod = ''
.head 5 -  Set ssMod = '1'
.head 5 -  Set i = pnExp
.head 5 -  Set lsFmt = ''
.head 5 +  While i >0
.head 6 -  Set ssMod = ssMod || '0'
.head 6 -  Set lsFmt = lsFmt || '0'
.head 6 -  Set i = i - 1
.head 5 -  Set lsTable = 'ID' || SalNumberToStrX( pnExp, 0 )
.head 5 -  Call SqlPrepareAndExecute( phSqlRecherche,
	"update	INC_NUM
	set	INC_NO_MAX = @mod( INC_NO_MAX + 1, " || ssMod || " )
	where	@upper( INC_TABLE ) = @upper( '" || lsTable || "' )
	and	INC_ANNEE = 0 ")
.head 5 -  Call SqlPrepareAndExecute( phSqlRecherche,
	"select	INC_NO_MAX
	from	INC_NUM
	where	@upper( INC_TABLE ) = @upper( '" || lsTable || "' )
	and	INC_ANNEE = 0
	into	:nVal ")
.head 5 +  If not SqlFetchNext( phSqlRecherche, nRet )
.head 6 -  Call SqlPrepareAndExecute( phSqlRecherche,
	"insert	into INC_NUM( inc_table, inc_no_max, inc_annee )
	values	( '" || lsTable || "', 0, 0 )")
.head 6 -  Set nVal = 0
.head 5 +  Else
.head 6 -  Set nVal = SalNumberMod( nVal, SalNumberPower( 10, pnExp ) )
.head 5 -  ! Set sRet = '#' || SalFmtFormatNumber( nVal, lsFmt )
.head 5 -  Set sRet = SalFmtFormatNumber( nVal, lsFmt )
.head 5 -  Return sRet
.head 2 +  Named Menus
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 1136075799
0000: 440B000027050000 0000000000000000 0200001A00FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F1D003C00 00085400496E634E
0040: 756D324080000000 0200000087040000 00F003000000FFDF 0420001900000001
0060: 00FC0000FF070180 3E00000800010000 0A636C0073426173 65436F6C009A0000
0080: 00050000006F0400 ED0200FFBF045900 040002FB00FF0F08 000000D6040002FE
00A0: 00FF830C00000019 B5000100FFFF6025 0000001900ED0100 FF3F0180603A0000
00C0: 000200F80D636C00 4466446174658400 D8000004005B1900 04FB00FF6F1900D6
00E0: 040002FE00FF931D 000004A100010200 00FF640100000100 6F01006021000000
0100: 1900ED0100FF3F01 80642100000300F8 11636C3F5469806D 656600000003BD00
0120: 19B5000400FFFF66 19000400ED0200FF BF1D190004000102 FB004F010000F601
0140: 0086010001802119 0004000C63026C43 6163686550206F6F 6C660000037B0084
0160: 0200000107000000 0101000806000000 0F80010000FE00CD 040004DA000300FF
0180: 7F08B200001900F6 0100FF1F01800432 00000500120C636C 624D756C0074694C
01A0: 616E677561006765 220000000100BD00 04B5000200FFFF18 0180040006006100
01C0: 18636C6800696C64 54626C4D75FF3F00 017A0000046B0002 00FFFF3101800400
01E0: 07C2000013636CFA 6F4DFFA300010000 B70400F60200FF1F 0180043300080013
0200: 8F6D624DFF3F0001 7A0000046B000200 FFFF310180040009 700000001244F866
0220: 4D75FFD100010000 5B040002FB00FF8F 01800481000A0000 0013876C674D75FF
0240: 1F000100BD0004B5 000200FFFF180180 04000B0038000013 4672F86D4D75FFD1
0260: 000100005B040002 FB00FF8F01800491 000C000012E34C62 4DFF8F000100DE00
0280: 04DA000200FF7F01 0C8004000D00001C 00134D6469FC4D75 FFE800010000AD04
02A0: 0002FD00FFC70180 04C0000E00000012 F36C4DFF47000100 006F0400ED0200FF
02C0: 3F01800604000F00 00008E124F624DFF 3F00017A0000046B 000200FFFF310180
02E0: 0400107000000012 50FC624DFFD10001 00005B040002FB00 FF8F018004010011
0300: 0000001D63026C51 75657374430E6857 6E644DFE757F00F4 010000D6040002FE
0320: 00FF6301800400E0 120000001D1F5461 62F06C65576EFF1F 000100BD0004B500
0340: 0200FFFF18018004 0013003000001263 5262FE4DFFE80001 0000AD040002FD00
0360: FFC7018004800014 0000001363E95462 4DFF8F000100DE00 04DA000200FF7F01
0380: 1080130100150000 00000F634465736B 74006F704C697374 426FD0784E01000B
03A0: DE0019D200010000 FF7F19B3001900F6 0100FF1F320000AC 00190001FD00FF07
03C0: 4B000000196B0001 00FFFFC164000000 19DA000100FF7F7D B00000001900F601
03E0: 00FF1F960000AC00 190001FD00FF07AF 000000196B000100 FFFFC1C800000019
0400: DA000100FF7FE1B0 0000001900F60100 FF1FFA0000AC0019 0001FD00FF870180
0420: 640004001600000B 6344F069724C69C1 7C00000004DE0019 D200010000FF7F19
0440: B3001900F60100FF DF32AC00190001FD 00FF374B00196B00 0100FFFF2101804B
0460: 000017F00000000F C0547265654C6907 5E000000037B0019 4B00010000FFFFCD
0480: 190019DA000100FF 7F32B3001900F601 00FF1F0180AF0200 00180000000CC063
04A0: 46696C654C0FD600 0000F60700961900 0100FE00FF9B1900 19B5000100FFFF66
04C0: 32001900ED0100FF BF4B5900190001FB 00FF6F6400D61900 01FE00FF9B7D0019
04E0: B5000100FFFF6696 001900ED0100FF3F 0180647D00001900 000D63526164696F
0500: 4C3E699A00D90005 005B190001FA0000 FF6F1900D6190001 FE00FF9B320019B5
0520: 000100FFFF664B00 1900ED0100FFBF64 5900190001FB00FF 0F
.enddata
.head 3 -  !
.head 3 -  !
.head 3 -  !
.head 3 +  Data Field Class: clsDFNumTVA
.head 4 -  Data
.head 5 -  Maximum Data Length: 14
.head 5 -  Data Type: String
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: 999.999.999
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template: C:\p_lib32\langue\qo_lang32.exe,frmPropertiesLanguage,,,N,N
.head 4 -  Class DLL Name:
.head 4 -  Description: Classe pour gérer les numéros de TVA
.head 4 +  Derived From
.head 5 -  Class: clsBaseDf
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  String: isValue
.head 5 -  Window Handle: iwhCmbPays
.head 5 -  String: isCodePays
.head 4 +  Functions
.head 5 +  Function: SetCmbPays
.head 6 -  Description: Donne le champ contenant le code du pays associé avec le n° de TVA
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  Window Handle: fwhCmbPays
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set iwhCmbPays = fwhCmbPays
.head 4 +  Message Actions
.head 5 +  On SAM_Validate
.head 6 -  ! Set wsPaysTVA = SalListQueryTextX( cmbTVA_PAYS, SalListQuerySelection( cmbTVA_PAYS ) )
.head 6 +  If iwhCmbPays = hWndNULL
.head 7 -  Call PalMessageBox( "Het veld met het BTW-nummer moet bijeengebracht worden", "Il faut associer le champ contenant le code du pays", 'Fout', 'Erreur', MB_Ok )
.head 7 -  Return VALIDATE_Cancel
.head 6 -  Call SalFmtFieldToStr( iwhCmbPays, isCodePays, FALSE )
.head 6 -  Set isCodePays = iwhCmbPays.clsCMBPaysTVA.isValue
.head 6 -  Set isCodePays = SalListQueryTextX( iwhCmbPays, SalListQuerySelection( iwhCmbPays ) )
.head 6 +  If SalIsNull( hWndItem )
.head 7 -  Return VALIDATE_Ok
.head 6 -  Call SalFmtFieldToStr( hWndItem, isValue, FALSE )
.head 6 -  Set isValue = MyValue
.head 6 +  If isCodePays = 'BE'
.head 7 +  If PalCheckCpt97( SalStrToNumber( MyValue ) )
.head 8 -  Return VALIDATE_Ok
.head 7 +  Else
.head 8 -  Call PalMessageBox( 'Het BTW-nummer is onjuist', "Le numéro de T.V.A est incorrecte.", 'Fout', 'Erreur', MB_Ok | MB_IconStop )
.head 8 -  ! Call SelectionTextDF( hWndItem )
.head 8 -  Return VALIDATE_Cancel
.head 6 +  Else If isCodePays = 'LU'
.head 7 +  If PalCheckCpt97( SalStrToNumber( MyValue ) )
.head 8 -  Return VALIDATE_Ok
.head 7 +  Else
.head 8 -  Call PalMessageBox( 'Het BTW-nummer is onjuist', "Le numéro de T.V.A est incorrecte.", 'Fout', 'Erreur', MB_Ok | MB_IconStop )
.head 8 -  ! Call SelectionTextDF( hWndItem )
.head 8 -  Return VALIDATE_Cancel
.head 6 +  Else
.head 7 -  Return VALIDATE_Ok
.head 3 +  Combo Box Class: clsCMBPaysTVA
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? No
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template: C:\p_lib32\langue\qo_lang32.exe,frmPropertiesLanguage,,,N,N
.head 4 -  Class DLL Name:
.head 4 -  Description: Combobox pour gérer les numéro de tva des pays.

Il faut charger le cache avec  "cat_tva" et "cat_tva_fmt"
.head 4 +  Derived From
.head 5 -  Class: clsBaseCmb
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  String: isValue
.head 5 -  Window Handle: iwhNumTVA
.head 5 -  String: isFmtTVA
.head 5 -  !
.head 5 -  String: isTmp
.head 5 -  Number: inTmp
.head 4 +  Functions
.head 5 +  Function: SetNumTVA
.head 6 -  Description: Donne le champ contenant le n° de TVA associé avec pays
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  Window Handle: fwhNumTVA
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set iwhNumTVA = fwhNumTVA
.head 5 +  Function: SetValue
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  String: psVal
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set isDbValue = psVal
.head 7 -  Call LookupDisplayValue( )
.head 7 +  If iwhNumTVA != hWndNULL
.head 8 -  Set isFmtTVA = 'XXXXXXXXXXXX'
.head 8 -  Call gCacheMgr.LookupElement( 'cat_tva_fmt', isDbValue, inTmp, isFmtTVA, isTmp, isTmp )
.head 8 -  Call SalFmtSetInputMask( iwhNumTVA, isFmtTVA )
.head 7 -  Set isValue = psVal
.head 4 -  List Initialization
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  ! Bepaal tabel voor drop down list
.head 6 -  Call SetTableName('cat_tva')
.head 6 -  !
.head 6 -  Call SalSendClassMessageNamed( clsBaseCmb, SAM_Create, wParam, lParam )
.head 6 -  !
.head 5 +  On SAM_Click
.head 6 +  If wParam != 100
.head 7 -  Call SalSendClassMessageNamed( clsBaseCmb, SAM_Click, wParam, lParam )
.head 6 +  If iwhNumTVA = hWndNULL
.head 7 -  Call PalMessageBox( "Het veld met het BTW-nummer moet bijeengebracht worden", "Il faut associer le champ contenant le numéro de TVA", 'Fout', 'Erreur', MB_Ok )
.head 7 -  Return FALSE
.head 6 -  Set isFmtTVA = 'XXXXXXXXXXXX'
.head 6 -  Call gCacheMgr.LookupElement( 'cat_tva_fmt', isDbValue, inTmp, isFmtTVA, isTmp, isTmp )
.head 6 -  Call SalFmtSetInputMask( iwhNumTVA, isFmtTVA )
.head 6 -  Set isValue = MyValue
.head 5 +  On SAM_AnyEdit
.head 6 -  Call SalSendClassMessageNamed( clsBaseCmb, SAM_AnyEdit, wParam, lParam )
.head 6 +  If iwhNumTVA = hWndNULL
.head 7 -  Call PalMessageBox( "Het veld met het BTW-nummer moet bijeengebracht worden", "Il faut associer le champ contenant le numéro de TVA", 'Fout', 'Erreur', MB_Ok )
.head 7 -  Return FALSE
.head 6 -  Set isFmtTVA = 'XXXXXXXXXXXX'
.head 6 -  Call gCacheMgr.LookupElement( 'cat_tva_fmt', isDbValue, inTmp, isFmtTVA, isTmp, isTmp )
.head 6 -  Call SalFmtSetInputMask( iwhNumTVA, isFmtTVA )
.head 6 -  Set isValue = MyValue
.head 3 +  Data Field Class: cNumIdentAnnee
.head 4 -  Data
.head 5 -  Maximum Data Length: 8
.head 5 -  Data Type: Number
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  1.017"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Right
.head 5 -  Format: #0
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: 99/999999
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template: C:\p_lib32\langue\qo_lang32.exe,frmPropertiesLanguage,,,N,N
.head 4 -  Class DLL Name:
.head 4 -  Description: Classe permettant la gestion des numéros identifiants
les factures, bons de commandes, ...

.head 4 +  Derived From
.head 5 -  Class: clsBaseDf
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  Number: nChiffre
.head 5 -  String: str
.head 5 -  Number: n
.head 5 -  Boolean: bAnnee
.head 4 +  Functions
.head 5 +  Function: VerifNum
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: nLong
.head 7 -  String: strNum
.head 7 -  Number: nLen
.head 6 +  Actions
.head 7 -  Set bAnnee = FALSE
.head 7 -  Call SalGetWindowText( hWndItem, strNum, 255 )
.head 7 -  Set strNum = VisStrSubstitute( strNum, '/', '' )
.head 7 -  Set nLong = SalStrLength( strNum )
.head 7 +  If nLong <=   nChiffre - 2
.head 8 -  Set bAnnee = TRUE
.head 8 -  Return TRUE
.head 7 +  Else If nLong = nChiffre
.head 8 -  Return TRUE
.head 7 -  Return TRUE
.head 5 +  Function: SetColor
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Number:
.head 6 +  Parameters
.head 7 -  Number: pnColorDefault
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If SalStrLeftX ( str, 1 ) = 'I'
.head 8 -  Call SalColorSet( hWndItem, COLOR_IndexWindow, COLOR_Maize )
.head 8 -  Return SalStrToNumber ( SalStrRightX ( str, SalStrLength ( str ) - 1 ) )
.head 7 +  Else
.head 8 -  Call SalColorSet( hWndItem, COLOR_IndexWindow, pnColorDefault )
.head 8 +  If str = ''
.head 9 -  Return NUMBER_Null
.head 8 +  Else
.head 9 -  Return SalStrToNumber ( str )
.head 5 +  Function: StrSetNum
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  String: sNum
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  String: lsOld
.head 6 +  Actions
.head 7 -  Call SalGetWindowText( hWndItem, lsOld, 255 )
.head 7 -  Call SalSetWindowText( hWndItem, sNum )
.head 7 +  If SalIsValidInteger( hWndItem )
.head 8 -  Set str = sNum
.head 8 -  Call SalSendMsg( hWndItem, SAM_Validate, 0, 0 )
.head 7 +  Else
.head 8 -  Call SalSetWindowText( hWndItem, lsOld )
.head 5 +  Function: LBFDisableInit
.head 6 -  Description: Permet de définir l'initialisation par défaut d'un type de zone.
.head 6 -  Returns
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Call clsDisableField.LBFDisableInit(  )
.head 7 +  If not ibInitTextCol[ TRUE ]
.head 8 -  Call DisableSetTextColor( TRUE, COLOR_Red )
.head 7 +  If not ibInitTextCol[ FALSE ]
.head 8 -  Call DisableSetTextColor( FALSE, COLOR_Red )
.head 5 -  !
.head 5 -  !
.head 5 +  Function: EstInterne
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return SalStrLeftX ( str, 1 ) = 'I'
.head 5 +  Function: CouleurFond
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  Number: pwParam
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If DisableIsState( pwParam )
.head 8 +  If EstInterne( )
.head 9 -  Call DisableSetBackgroundColor( TRUE, COLOR_Maize )
.head 8 +  Else
.head 9 -  Call DisableSetBackgroundColor( TRUE, DisableDefBackgroundColor( TRUE ) )
.head 4 +  Message Actions
.head 5 +  On SAM_Validate
.head 6 +  If SalIsNull( hWndItem )
.head 7 -  Set n = NUMBER_Null
.head 7 -  Set str = ''
.head 7 -  Return VALIDATE_Ok
.head 6 -  Set nChiffre = SalGetMaxDataLength( hWndItem )
.head 6 +  If nChiffre <= 0
.head 7 -  Set nChiffre = 8
.head 6 +  If VerifNum( )
.head 7 -  Call SalFmtFieldToStr( hWndItem, str, FALSE )
.head 7 -  Set n = SalStrToNumber( str )
.head 7 +  If bAnnee and ( n < SalNumberPower( 10, nChiffre - 2 ) )
.head 8 -  Set n = SalNumberMod( SalStrToNumber( gsAnneeBudgetaire ) , 100 ) * SalNumberPower( 10, nChiffre - 2 ) + n
.head 7 -  Set str = SalStrRightX( SalStrRepeatX( '0', nChiffre ) || SalFmtFormatNumber( n, '0' ), nChiffre )
.head 7 -  Set MyValue = n
.head 7 -  Return VALIDATE_Ok
.head 6 +  Else
.head 7 -  Return VALIDATE_Cancel
.head 5 +  On PAM_Clear
.head 6 -  Call SalSendClassMessageNamed ( clsBaseDf, PAM_Clear, wParam, lParam )
.head 6 -  Set n = NUMBER_Null
.head 6 -  Set str = ''
.head 5 +  On PAM_DisableField
.head 6 -  Call CouleurFond( wParam )
.head 6 -  Call SalSendClassMessage( PAM_DisableField, wParam, lParam )
.head 3 +  Functional Class: TIncNum2
.head 4 -  Description: Obtenir un numéro de séquence dans la table inc_num
.head 4 -  Derived From
.head 4 +  Class Variables
.head 5 -  Sql Handle: hSql
.head 5 -  ! Sql Handle: hSql2
.head 5 -  Boolean: bConnect
.head 4 -  Instance Variables
.head 4 +  Functions
.head 5 +  Function: Init
.head 6 -  Description:
.head 6 -  Returns
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  String: s
.head 6 +  Actions
.head 7 +  If bConnect
.head 8 -  Call Term( )
.head 7 -  Set s = PalGetTransactionName(  )
.head 7 -  Set bConnect = PalSqlConnectTransaction( hSql, s )
.head 7 +  If bConnect
.head 8 -  Call SqlSetParameter( hSql, DBP_AUTOCOMMIT, FALSE, '' )
.head 8 -  Call SqlSetParameter( hSql, DBP_PRESERVE, TRUE, '' )
.head 8 -  Call SqlSetIsolationLevel( hSql, 'RL' )
.head 5 +  Function: Term
.head 6 -  Description:
.head 6 -  Returns
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If bConnect
.head 8 -  Call Commit( )
.head 8 -  Call SqlDisconnect( hSql )
.head 8 -  Set bConnect = FALSE
.head 5 +  Function: Commit
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If bConnect
.head 8 -  Return SqlPrepareAndExecute( hSql, "commit" )
.head 7 +  Else
.head 8 -  Return FALSE
.head 5 +  Function: Rollback
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If bConnect
.head 8 -  Return SqlPrepareAndExecute( hSql, "rollback" )
.head 7 +  Else
.head 8 -  Return FALSE
.head 5 +  Function: GetNum
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Number:
.head 6 +  Parameters
.head 7 -  String: spAnnee
.head 7 -  String: spTable
.head 7 -  Number: npExp
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: nRet
.head 7 -  Number: n
.head 7 -  Boolean: bOkNum
.head 7 -  Number: nBcl
.head 7 -  String: s
.head 7 -  Number: nVal
.head 7 -  Number: inCount
.head 6 +  Actions
.head 7 -  Set bOkNum = FALSE
.head 7 -  Set nBcl = 1000
.head 7 +  If not bConnect
.head 8 -  Call Init( )
.head 7 +  If bConnect
.head 8 +  When SqlError
.head 9 -  Return FALSE
.head 8 +  While not bOkNum and nBcl
.head 9 -  Set nBcl = nBcl - 1
.head 9 +  If SqlPrepareAndExecute( hSql,
	"select count( * ) from inc_num
	where	@upper( INC_TABLE ) = @upper( '" || spTable || "' ) and INC_ANNEE = :spAnnee
	into	:inCount" )
.head 10 -  Call SqlFetchNext( hSql, nRet )
.head 9 +  If SqlPrepareAndExecute( hSql,
	"update INC_NUM
	set	INC_NO_MAX = INC_NO_MAX + 1
	where	@upper( INC_TABLE ) = @upper( '" || spTable || "' ) and INC_ANNEE = :spAnnee" )
.head 10 +  If SqlPrepareAndExecute( hSql,
	"select	INC_NO_MAX - 1
	from	INC_NUM
	where	@upper( INC_TABLE ) = @upper( '" || spTable || "' ) and INC_ANNEE = :spAnnee
	into	:n
	" )
.head 11 +  If SqlFetchNext( hSql, nRet )
.head 12 -  Set s = SalStrRightX( spAnnee, 2 ) || SalFmtFormatNumber( n, '000000' )
.head 12 -  Set bOkNum = TRUE
.head 12 -  Call Commit (  )
.head 11 +  Else
.head 12 -  Call Rollback( )
.head 10 +  Else
.head 11 -  Call Rollback( )
.head 8 +  If bOkNum
.head 9 -  Set nVal = SalNumberMod( SalStrToNumber( spAnnee ), 100 ) * SalNumberPower( 10, npExp ) + n
.head 9 -  Return nVal
.head 8 +  Else
.head 9 -  Return -1
.head 7 +  Else
.head 8 -  Return -1
.head 5 +  Function: ReleaseNum
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Number:
.head 6 +  Parameters
.head 7 -  String: spTable
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: nRet
.head 7 -  Number: n
.head 6 +  Actions
.head 7 +  If bConnect
.head 8 -  Call SqlPrepareAndExecute( hSql,
	"select	INC_NO_MAX
	from	INC_NUM
	where	@upper( INC_TABLE ) = @upper( '" || spTable || "' ) and INC_ANNEE = :spAnnee
	into	:n
	" )
.head 8 +  If SqlFetchNext( hSql, nRet )
.head 9 -  Call SqlPrepareAndExecute( hSql,
	"update INC_NUM
	set	INC_NO_MAX = INC_NO_MAX - 1
	where	@upper( INC_TABLE ) = @upper( '" || spTable || "' ) and INC_ANNEE = :spAnnee" )
.head 9 -  Return 0
.head 8 +  Else
.head 9 -  Call Rollback( )
.head 9 -  Return -1
.head 7 +  Else
.head 8 -  Return -1
.head 5 +  ! Function: GetNumU
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Number:
.head 6 +  Parameters
.head 7 -  String: spTable
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: nRet
.head 7 -  Number: n
.head 6 +  Actions
.head 7 +  If not bConnect
.head 8 -  Call Init( )
.head 7 +  If bConnect
.head 8 -  ! /##### UCCLE : 31/12/96
.head 8 -  ! Call SqlPrepareAndExecute( hSql,
	"select	NUM_MAX
	from	INC_NUM
	where	NOM_TABLE = :spTable
	into	:n
	for update of	NUM_MAX" )
.head 8 -  Call SqlPrepareAndExecute( hSql,
	"select	NUM_MAX
	from	INC_NUM
	where	ANNEE = :spAnnee
	and	NOM_TABLE = :spTable
	into	:n
	for update of	NUM_MAX" )
.head 8 -  ! \##### UCCLE : 31/12/96
.head 8 +  If SqlFetchNext( hSql, nRet )
.head 9 -  Call SqlPrepareAndExecute( hSql,
	"update INC_NUM
	set	NUM_MAX = NUM_MAX + 1
	where	NOM_TABLE = :spTable and ANNEE = :spAnnee" )
.head 9 -  Return n
.head 8 +  Else
.head 9 -  Call Rollback( )
.head 9 -  Return -1
.head 7 +  Else
.head 8 -  Return -1
.head 3 +  Picture Class: clsPictureTip
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  File Name:
.head 4 -  Storage: Class Default
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Fit: Class Default
.head 4 -  Scaling
.head 5 -  Width:  Class Default
.head 5 -  Height:  Class Default
.head 4 -  Corners: Class Default
.head 4 -  Border Style: Class Default
.head 4 -  Border Thickness: Class Default
.head 4 -  Tile To Parent? Class Default
.head 4 -  Border Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template: ,,,,N,N
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  ! Class: CWC_CS_ToolTip
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 -  Message Actions
.head 3 -  !
.head 3 -  !
.head 3 -  !
.head 3 +  Data Field Class: clsBaseDfMontant
.data CLASSPROPS
0000: 4C6162656C640002 003A00004C616265 6C660009004D6F6E 74616E743A00004C
0020: 6162656C6E000800 4265647261673A00 004C6162656C6500 02003A0000546162
0040: 4368696C644E616D 65730006004E616D 6530000000000000 000000000000
.enddata
.data CLASSPROPSSIZE
0000: 5E00
.enddata
.data INHERITPROPS
0000: 0100
.enddata
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: Number
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 8.133"
.head 6 -  Top: 1.095"
.head 6 -  Width:  1.533"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Class Default
.head 5 -  Border? Yes
.head 5 -  Justify: Right
.head 5 -  Format: ###000
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Unformatted
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template: C:\p_lib32\langue\qo_lang32.exe,frmPropertiesLanguage,,,N,N
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsBaseDf
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  Boolean: ibEuro
.head 5 -  Number: ihAccel
.head 5 -  Number: inResult
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_Euro
.head 6 +  If gbEuro or ibEuro
.head 7 -  Call SalFmtSetPicture( hWndItem, C_FMT_EURO )
.head 6 +  Else
.head 7 -  Call SalFmtSetPicture( hWndItem, C_FMT_BEF )
.head 6 +  If lParam = 999999
.head 7 +  If SalModalDialog( dlgMttBefEuro, hWndItem, MyValue, inResult )
.head 8 -  Set MyValue = inResult
.head 5 +  On SAM_Create
.head 6 -  Call SalSendMsg( hWndItem, PAM_Euro, wParam, lParam )
.head 5 +  On SAM_SetFocus
.head 6 -  Set gwhWndEuro = hWndItem
.head 6 +  If ihAccel = 0
.head 7 -  ! Set ihAccel = VisWinLoadAccelerator( hWndItem, PAM_Euro, KDS_None, VK_F5, 999999 )
.head 7 -  Set ihAccel = VisWinLoadAccelerator( gwhWndEuro, PAM_Euro, KDS_None, VK_F5, 999999 )
.head 5 +  On SAM_KillFocus
.head 6 -  Call VisWinFreeAccelerator( ihAccel )
.head 6 -  Set ihAccel = 0
.head 6 -  Set gwhWndEuro = hWndNULL
.head 3 +  Column Class: clsBaseColMontant
.head 4 -  Title:
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Data Type: Number
.head 4 -  Justify: Right
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Format: Class Default
.head 4 -  Country: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Cell Options
.head 5 -  Cell Type? Class Default
.head 5 -  Multiline Cell? Class Default
.head 5 -  Cell DropDownList
.head 6 -  Sorted? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Auto Drop Down? Class Default
.head 6 -  Allow Text Editing? Class Default
.head 5 -  Cell CheckBox
.head 6 -  Check Value:
.head 6 -  Uncheck Value:
.head 6 -  Ignore Case? Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsBaseCol
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  Boolean: ibEuro
.head 5 -  Number: ihAccel
.head 5 -  Number: inResult
.head 4 -  Functions
.head 4 -  List Values
.head 4 +  Message Actions
.head 5 +  On PAM_Euro
.head 6 +  If gbEuro or ibEuro
.head 7 -  Call SalFmtSetPicture( hWndItem, C_FMT_EURO )
.head 6 +  Else
.head 7 -  Call SalFmtSetPicture( hWndItem, C_FMT_BEF )
.head 6 +  If lParam = 999999
.head 7 +  If SalModalDialog( dlgMttBefEuro, hWndItem, MyValue, inResult )
.head 8 -  Set MyValue = inResult
.head 5 +  On SAM_Create
.head 6 -  Set ibEuro = TRUE
.head 6 -  Call SalSendMsg( hWndItem, PAM_Euro, wParam, lParam )
.head 5 +  On SAM_SetFocus
.head 6 +  If ihAccel = 0
.head 7 -  Set ihAccel = VisWinLoadAccelerator( hWndItem, PAM_Euro, KDS_None, VK_F5, 999999 )
.head 6 -  Set gwhWndEuro = hWndItem
.head 5 +  On SAM_KillFocus
.head 6 -  Call VisWinFreeAccelerator( ihAccel )
.head 6 -  Set ihAccel = 0
.head 6 -  Set gwhWndEuro = hWndItem
.head 3 +  Data Field Class: clsBaseDfROMontant
.data CLASSPROPS
0000: 4C6162656C640002 003A00004C616265 6C660009004D6F6E 74616E743A00004C
0020: 6162656C6E000800 4265647261673A00 004C6162656C6500 02003A0000546162
0040: 4368696C644E616D 65730006004E616D 6530000000000000 000000000000
.enddata
.data CLASSPROPSSIZE
0000: 5E00
.enddata
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Number
.head 5 -  Editable? No
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  1.483"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Right
.head 5 -  Format: ###0
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: 3D Face Color
.head 5 -  Input Mask: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template: \p_lib32\langue\qo_lang32.exe,frmPropertiesLanguage,,,N,N
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsBaseDfMontant
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 -  Message Actions
.head 3 +  Data Field Class: clsBaseDfMontantOri
.data CLASSPROPS
0000: 4C6162656C640002 003A00004C616265 6C660009004D6F6E 74616E743A00004C
0020: 6162656C6E000800 4265647261673A00 004C6162656C6500 02003A0000546162
0040: 4368696C644E616D 65730006004E616D 6530000000000000 000000000000
.enddata
.data CLASSPROPSSIZE
0000: 5E00
.enddata
.data INHERITPROPS
0000: 0100
.enddata
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: Number
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 8.133"
.head 6 -  Top: 1.095"
.head 6 -  Width:  1.533"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Class Default
.head 5 -  Border? Yes
.head 5 -  Justify: Right
.head 5 -  Format: ###0
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Unformatted
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template: C:\p_lib32\langue\qo_lang32.exe,frmPropertiesLanguage,,,N,N
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsBaseDf
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 -  Message Actions
.head 3 +  ! Data Field Class: clsBaseDfDateComptableOri
.winattr
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: Date/Time
.head 5 -  Editable? Yes
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  1.2"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? Yes
.head 5 -  Justify: Center
.head 5 -  Format: dd/MM/yyyy
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Input Mask: Unformatted
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template: C:\P_LIB\LANGUE\QO_LANG.EXE,frmPropertiesLanguage,,,N,N
.head 4 -  Class DLL Name: QUIKPDLG.DLL
.end
.head 4 -  Description: 
.head 4 +  Derived From 
.head 5 -  Class: clsBaseDfDate
.head 4 -  Class Variables 
.head 4 -  Instance Variables 
.head 4 -  Functions 
.head 4 +  Message Actions 
.head 5 +  On SAM_Create
.head 6 -  Set MyValue = SalDateCurrent (  )
.head 6 +  If SalNumberToStrX ( SalDateYear ( MyValue ), 0 ) > gsAnneeBudgetaire
.head 7 -  Set MyValue = SalDateConstruct ( SalStrToNumber ( gsAnneeBudgetaire ), 12, 31, 0, 0, 0 )
.head 6 -  ! ## MARC 17/12/1997>>
.head 6 +  Else If SalNumberToStrX ( SalDateYear ( MyValue ), 0 ) < gsAnneeBudgetaire
.head 7 -  ! /@@@@@ LS : 26/12/97
.head 7 -  ! Date doit être le 2 janvier au plus tot
.head 7 -  Set MyValue = SalDateConstruct ( SalStrToNumber ( gsAnneeBudgetaire), 1, 2, 0, 0, 0 )
.head 7 -  ! \@@@@@ LS : 26/12/97
.head 6 -  ! ## MARC 17/12/1997<<
.head 5 +  On PAM_Clear
.head 6 -  Call SalSendClassMessageNamed ( clsBaseDfDate, PAM_Clear, wParam, lParam )
.head 6 -  Set MyValue = SalDateCurrent (  )
.head 6 +  If SalNumberToStrX ( SalDateYear ( MyValue ), 0 ) > gsAnneeBudgetaire
.head 7 -  Set MyValue = SalDateConstruct ( SalStrToNumber ( gsAnneeBudgetaire ), 12, 31, 0, 0, 0 )
.head 6 -  ! ## MARC 17/12/1997>>
.head 6 +  Else If SalNumberToStrX ( SalDateYear ( MyValue ), 0 ) < gsAnneeBudgetaire
.head 7 -  ! /@@@@@ LS : 26/12/97
.head 7 -  ! Date doit être le 2 janvier au plus tot
.head 7 -  Set MyValue = SalDateConstruct ( SalStrToNumber ( gsAnneeBudgetaire), 1, 2, 0, 0, 0 )
.head 7 -  ! \@@@@@ LS : 26/12/97
.head 6 -  ! ## MARC 17/12/1997<<
.head 5 +  On SAM_Validate
.head 6 +  If SalNumberToStrX ( SalDateYear ( MyValue ), 0 ) > gsAnneeBudgetaire
.head 7 -  Call PalMessageBox ( "Libelle NL.", "L'année de la date comptable est incorrecte.", C_OPGELET, C_ATTENTION, MB_Ok | MB_IconExclamation )
.head 7 -  Return VALIDATE_Cancel
.head 6 +  Else If SalIsValidDateTime( MyValue )
.head 7 -  ! ## MARC 17/12/1997>>
.head 7 +  If SalNumberToStrX ( SalDateYear ( MyValue ), 0 ) < gsAnneeBudgetaire
.head 8 -  Set MyValue = SalDateConstruct ( SalStrToNumber ( gsAnneeBudgetaire), 1, 2, 0, 0, 0 )
.head 7 -  ! ## MARC 17/12/1997<<
.head 7 -  ! /@@@@@ LS : 26/12/97
.head 7 +  If SalNumberToStrX ( SalDateYear ( MyValue ), 0 ) > gsAnneeBudgetaire
.head 8 -  Set MyValue = SalDateConstruct ( SalStrToNumber ( gsAnneeBudgetaire ), 12, 31, 0, 0, 0 )
.head 7 -  ! \@@@@@ LS : 26/12/97
.head 7 -  Return VALIDATE_Ok
.head 6 +  Else 
.head 7 -  Call PalMessageBox ( LIB_NL, "La date est incorrecte.", C_OPGELET, C_ATTENTION, MB_Ok | MB_IconExclamation )
.head 7 -  Return VALIDATE_Cancel
.head 2 +  Default Classes
.head 3 -  MDI Window: cBaseMDI
.head 3 -  Form Window:
.head 3 -  Dialog Box: clsBaseDlg
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field: clsBaseDfMontant
.head 3 -  Spin Field:
.head 3 -  Multiline Field: cQuickMLField
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Option Button:
.head 3 -  ActiveX:
.head 3 -  Check Box:
.head 3 -  Child Table: cQuickTable
.head 3 -  Quest Child Window: cQuickDatabase
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture: cQuickPicture
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control: cQuickGraph
.head 2 -  Application Actions
.head 1 +  Dialog Box: dlgMttBefEuro
.head 2 -  Class:
.head 2 -  Property Template: \P_LIB32\LANGUE\QO_LANG32.EXE,frmPropertiesLanguage,,,N,N
.head 2 -  Class DLL Name:
.head 2 -  Title: Conversion BEF <-> Euro
.head 2 -  Accessories Enabled? No
.head 2 -  Visible? Yes
.head 2 -  Display Settings
.head 3 -  Display Style? Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 3.713"
.head 4 -  Top: 1.76"
.head 4 -  Width:  4.033"
.head 4 -  Width Editable? Yes
.head 4 -  Height: 1.623"
.head 4 -  Height Editable? Yes
.head 3 -  Absolute Screen Location? Yes
.head 3 -  Font Name: Default
.head 3 -  Font Size: Default
.head 3 -  Font Enhancement: Default
.head 3 -  Text Color: Default
.head 3 -  Background Color: Default
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Default
.head 4 -  Location? Top
.head 4 -  Visible? Yes
.head 4 -  Size: Default
.head 4 -  Size Editable? Yes
.head 4 -  Docking Toolbar? No
.head 4 -  Toolbar Docking Orientation: Top | Bottom
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 3 -  Contents
.head 2 +  Contents
.head 3 -  Background Text: BEF
.head 4 -  Resource Id: 11470
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.517"
.head 5 -  Top: 0.345"
.head 5 -  Width:  0.833"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Left
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 3 +  Data Field: dfBef
.data CLASSPROPS
0000: 5461624368696C64 4E616D6573000600 4E616D653000004C 6162656C65000100
0020: 00004C6162656C6E 00010000004C6162 656C660001000000 4C6162656C640001
0040: 0000000000000000 0000000000
.enddata
.data CLASSPROPSSIZE
0000: 4D00
.enddata
.data INHERITPROPS
0000: 0100
.enddata
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsBaseDfMontant
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 1.617"
.head 6 -  Top: 0.321"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 +  Message Actions
.head 5 +  On SAM_AnyEdit
.head 6 -  Set dfEuro = ToEuro( dfBef )
.head 5 -  On SAM_SetFocus
.head 5 -  On SAM_KillFocus
.head 3 -  Background Text: Euro
.head 4 -  Resource Id: 11471
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.517"
.head 5 -  Top: 0.655"
.head 5 -  Width:  0.833"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Left
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 3 +  Data Field: dfEuro
.data CLASSPROPS
0000: 5461624368696C64 4E616D6573000600 4E616D653000004C 6162656C65000100
0020: 00004C6162656C6E 00010000004C6162 656C660001000000 4C6162656C640001
0040: 0000000000000000 0000000000
.enddata
.data CLASSPROPSSIZE
0000: 4D00
.enddata
.data INHERITPROPS
0000: 0100
.enddata
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsBaseDfMontant
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 1.617"
.head 6 -  Top: 0.631"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set ibEuro = TRUE
.head 5 +  On SAM_AnyEdit
.head 6 -  Set dfBef = ToBEF( dfEuro )
.head 5 -  On SAM_SetFocus
.head 5 -  On SAM_KillFocus
.head 3 +  Pushbutton: pbOk
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: &Ok
.head 4 -  Window Location and Size
.head 5 -  Left: 0.433"
.head 5 -  Top: 1.071"
.head 5 -  Width:  1.2"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.298"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Keyboard Accelerator: Enter
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Picture File Name:
.head 4 -  Picture Transparent Color: None
.head 4 -  Image Style: Single
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 4 -  Button Appearance: Standard
.head 4 +  Message Actions
.head 5 +  On SAM_Click
.head 6 +  If gbEuro
.head 7 -  Set pnrResultat = dfEuro
.head 6 +  Else
.head 7 -  Set pnrResultat = dfBef
.head 6 -  Call SalEndDialog( hWndForm, TRUE )
.head 3 +  Pushbutton: pbCancel
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: Annuler
.head 4 -  Window Location and Size
.head 5 -  Left: 2.35"
.head 5 -  Top: 1.071"
.head 5 -  Width:  1.2"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.298"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Keyboard Accelerator: Esc
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Picture File Name:
.head 4 -  Picture Transparent Color: None
.head 4 -  Image Style: Single
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 4 -  Button Appearance: Standard
.head 4 +  Message Actions
.head 5 +  On SAM_Click
.head 6 -  Call SalEndDialog( hWndForm, FALSE )
.head 2 -  Functions
.head 2 +  Window Parameters
.head 3 -  Number: pnValeur
.head 3 -  Receive Number: pnrResultat
.head 2 -  Window Variables
.head 2 +  Message Actions
.head 3 +  On SAM_Create
.head 4 -  Call SalCenterWindow( hWndForm )
.head 4 -  Call SalSetFocus( dfEuro )
.head 4 +  If pnValeur != NUMBER_Null
.head 5 +  If gbEuro
.head 6 -  Set dfEuro = pnValeur
.head 6 -  Set dfBef = ToBEF( dfEuro )
.head 6 -  Call SalSetFocus( dfBef )
.head 6 -  Call SalPostMsg( dfBef, EM_SETSEL, 0, -65536 )
.head 5 +  Else
.head 6 -  Set dfBef = pnValeur
.head 6 -  Set dfEuro = ToEuro( dfBef )
.head 6 -  Call SalSetFocus( dfEuro )
.head 6 -  Call SalPostMsg( dfEuro, EM_SETSEL, 0, -65536 )
.head 4 +  Else
.head 5 -  Set dfBef = 0
.head 5 -  Set dfEuro = 0.00
.head 5 -  Call SalPostMsg( dfEuro, EM_SETSEL, 0, -65536 )
.head 1 +  Dialog Box: dlgRealeaseEnCours
.head 2 -  Class:
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Avertissement
.head 2 -  Accessories Enabled? No
.head 2 -  Visible? Yes
.head 2 -  Display Settings
.head 3 -  Display Style? Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 2.375"
.head 4 -  Top: 1.563"
.head 4 -  Width:  8.667"
.head 4 -  Width Editable? Yes
.head 4 -  Height: 3.048"
.head 4 -  Height Editable? Yes
.head 3 -  Absolute Screen Location? Yes
.head 3 -  Font Name: MS Sans Serif
.head 3 -  Font Size: 8
.head 3 -  Font Enhancement: Default
.head 3 -  Text Color: Default
.head 3 -  Background Color: Default
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Default
.head 4 -  Location? Top
.head 4 -  Visible? Yes
.head 4 -  Size: Default
.head 4 -  Size Editable? Yes
.head 4 -  Docking Toolbar? No
.head 4 -  Toolbar Docking Orientation: Top | Bottom
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 3 -  Contents
.head 2 +  Contents
.head 3 -  Background Text: ATTENTION
.head 4 -  Resource Id: 5614
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.1"
.head 5 -  Top: 0.226"
.head 5 -  Width:  8.3"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.262"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Center
.head 4 -  Font Name: Default
.head 4 -  Font Size: 12
.head 4 -  Font Enhancement: Bold
.head 4 -  Text Color: Red
.head 4 -  Background Color: Default
.head 3 +  Data Field: df1
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: String
.head 5 -  Editable? No
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 0.1"
.head 6 -  Top: 0.679"
.head 6 -  Width:  8.367"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? No
.head 5 -  Justify: Left
.head 5 -  Format: Unformatted
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Default
.head 5 -  Background Color: 3D Face Color
.head 5 -  Input Mask: Unformatted
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set MyValue = 'Une mise-à-jour ' || psTypeMAJ
.head 3 +  Data Field: df2
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: String
.head 5 -  Editable? No
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 0.1"
.head 6 -  Top: 1.012"
.head 6 -  Width:  8.367"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? No
.head 5 -  Justify: Center
.head 5 -  Format: Unformatted
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Bold
.head 5 -  Text Color: Default
.head 5 -  Background Color: 3D Face Color
.head 5 -  Input Mask: Unformatted
.head 4 -  Message Actions
.head 3 +  Data Field: df3
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: String
.head 5 -  Editable? No
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 0.1"
.head 6 -  Top: 1.345"
.head 6 -  Width:  8.367"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? No
.head 5 -  Justify: Left
.head 5 -  Format: Unformatted
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Default
.head 5 -  Background Color: 3D Face Color
.head 5 -  Input Mask: Unformatted
.head 4 -  Message Actions
.head 3 +  Data Field: df4
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: Number
.head 5 -  Editable? No
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 0.167"
.head 6 -  Top: 2.631"
.head 6 -  Width:  0.967"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? No
.head 5 -  Justify: Left
.head 5 -  Format: Unformatted
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Default
.head 5 -  Background Color: 3D Face Color
.head 5 -  Input Mask: Unformatted
.head 4 -  Message Actions
.head 3 +  Pushbutton: pb1
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: Quitter
.head 4 -  Window Location and Size
.head 5 -  Left: 3.6"
.head 5 -  Top: 2.607"
.head 5 -  Width:  1.2"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.298"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Keyboard Accelerator: (none)
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Picture File Name:
.head 4 -  Picture Transparent Color: None
.head 4 -  Image Style: Single
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 4 -  Button Appearance: Standard
.head 4 +  Message Actions
.head 5 +  On SAM_Click
.head 6 +  If bEnCours
.head 7 +  If ( ( VisGetKeyState( VK_Control ) & KS_Down ) != 0 )
.head 8 -  Call SalEndDialog( hWndForm, TRUE )
.head 7 +  Else
.head 8 -  Call SalQuit(  )
.head 6 +  Else
.head 7 -  Call SalEndDialog( hWndForm, TRUE )
.head 5 +  On SAM_Timer
.head 6 -  Set df4 = df4 - 1
.head 6 +  If df4 = 0
.head 7 -  Call SalTimerKill( hWndItem, wParam )
.head 7 -  Call SalSendMsg( hWndItem, SAM_Click, 0, 0 )
.head 2 -  Functions
.head 2 +  Window Parameters
.head 3 -  String: psTypeMAJ
.head 3 -  String: psFileIni
.head 3 -  String: psTypePrgm
.head 2 +  Window Variables
.head 3 -  Date/Time: dt
.head 3 -  Boolean: bRelease
.head 3 -  Date/Time: dt2
.head 3 -  Number: nDelay
.head 3 -  String: s1
.head 3 -  String: s2
.head 3 -  String: s3
.head 3 -  String: s4
.head 3 -  String: s5
.head 3 -  String: s6
.head 3 -  Boolean: bEnCours
.head 3 -  Boolean: bHeure
.head 3 -  Number: nTimer
.head 2 +  Message Actions
.head 3 +  On SAM_Create
.head 4 -  Set bRelease = FALSE
.head 4 -  Call SalCenterWindow( hWndForm )
.head 4 -  Call SalGetProfileString( __RELEASE1, 'DateDeb', '', s1, psFileIni )
.head 4 -  Set nDelay = SalGetProfileInt( __RELEASE1, 'Delais', 1, psFileIni )
.head 4 -  Set nTimer = SalGetProfileInt( __RELEASE1, 'Timer', 15, psFileIni )
.head 4 -  Set bEnCours = FALSE
.head 4 -  Set bHeure = TRUE
.head 4 +  If s1 = ''
.head 5 -  Call SalEndDialog( hWndItem, TRUE )
.head 4 -  Set s2 = SalStrMidX( s1, 0, 4 )
.head 4 -  Set s3 = SalStrMidX( s1, 4, 2 )
.head 4 -  Set s4 = SalStrMidX( s1, 6, 2 )
.head 4 -  Set s5 = SalStrMidX( s1, 8, 2 )
.head 4 -  Set s6 = SalStrMidX( s1, 10, 2 )
.head 4 +  If s5 = ''
.head 5 -  Set s5 = __0
.head 5 -  Set bHeure = FALSE
.head 4 +  If s6 = ''
.head 5 -  Set s6 = __0
.head 5 -  Set bHeure = FALSE
.head 4 +  If not bHeure
.head 5 -  Set s6 = __0
.head 5 -  Set s5 = __0
.head 4 -  Set dt = SalDateConstruct( SalStrToNumber( s2 ), SalStrToNumber( s3 ), SalStrToNumber( s4 ), SalStrToNumber( s5 ), SalStrToNumber( s6 ), 0 )
.head 4 -  Set dt2 = SalDateCurrent(  )
.head 4 +  If ( ( dt2 - dt ) >= 0 ) and ( ( dt2 - dt ) < ( nDelay ) )
.head 5 -  Set df2 = 'est en-cours'
.head 5 -  Set df3 =  "Vous ne pouvez pas utiliser les programmes lors de cette mise-à-jour"
.head 5 -  Set bEnCours = TRUE
.head 5 -  Call SalSetWindowText( pb1, 'Quitter' )
.head 5 -  Set df4 = nTimer
.head 5 -  Call SalTimerSet( pb1, 1, 1000 )
.head 5 -  Set bRelease = TRUE
.head 4 +  Else
.head 5 -  Call SalSetWindowText( pb1, 'Continuer' )
.head 5 +  If bHeure
.head 6 -  Set df2 = 'aura lieu le ' || SalFmtFormatDateTime( dt, 'dd/MM/yyyy' ) || ' à '  || SalFmtFormatDateTime( dt, 'hhh:mm' )
.head 5 +  Else
.head 6 -  Set df2 = 'aura lieu le ' || SalFmtFormatDateTime( dt, 'dd/MM/yyyy' )
.head 5 -  Set df3 =  "Vous ne pourrez pas utiliser les programmes de cette application lors de cette mise-à-jour"
.head 5 -  Set dt2 = dt - 1
.head 5 +  Select Case SalDateWeekday( dt2 )
.head 6 +  Case 0
.head 7 -  Set dt2  = dt2 - 1
.head 6 +  Case 6
.head 7 -  Set dt2  = dt2 - 1
.head 7 -  Break
.head 5 +  If ( ( SalDateCurrent(  ) - dt2 ) >= 0 ) and ( ( SalDateCurrent(  ) - dt2  ) < 1 )
.head 6 -  Set bRelease = TRUE
.head 5 +  ! Else
.head 6 -  Call SalEndDialog( hWndItem, TRUE )
.head 4 +  If not bRelease
.head 5 -  Set df1 = df1 || ' ( '  || psTypePrgm || ' ) '
.head 5 -  Call SalGetProfileString( __RELEASE2 || psTypePrgm, 'DateDeb', '', s1, psFileIni )
.head 5 -  Set nDelay = SalGetProfileInt( __RELEASE2 || psTypePrgm, 'Delais', 1, psFileIni )
.head 5 -  Set nTimer = SalGetProfileInt( __RELEASE2 || psTypePrgm, 'Timer', 15, psFileIni )
.head 5 -  Set bEnCours = FALSE
.head 5 -  Set bHeure = TRUE
.head 5 +  If s1 = ''
.head 6 -  Call SalEndDialog( hWndItem, TRUE )
.head 5 -  Set s2 = SalStrMidX( s1, 0, 4 )
.head 5 -  Set s3 = SalStrMidX( s1, 4, 2 )
.head 5 -  Set s4 = SalStrMidX( s1, 6, 2 )
.head 5 -  Set s5 = SalStrMidX( s1, 8, 2 )
.head 5 -  Set s6 = SalStrMidX( s1, 10, 2 )
.head 5 +  If s5 = ''
.head 6 -  Set s5 = __0
.head 6 -  Set bHeure = FALSE
.head 5 +  If s6 = ''
.head 6 -  Set s6 = __0
.head 6 -  Set bHeure = FALSE
.head 5 +  If not bHeure
.head 6 -  Set s6 = __0
.head 6 -  Set s5 = __0
.head 5 -  Set dt = SalDateConstruct( SalStrToNumber( s2 ), SalStrToNumber( s3 ), SalStrToNumber( s4 ), SalStrToNumber( s5 ), SalStrToNumber( s6 ), 0 )
.head 5 -  Set dt2 = SalDateCurrent(  )
.head 5 +  If ( ( dt2 - dt ) >= 0 ) and ( ( dt2 - dt ) < ( nDelay ) )
.head 6 -  Set df2 = 'est en-cours'
.head 6 -  Set df3 =  "Vous ne pouvez pas utiliser les programmes lors de cette mise-à-jour"
.head 6 -  Set bEnCours = TRUE
.head 6 -  Call SalSetWindowText( pb1, 'Quitter' )
.head 6 -  Set df4 = nTimer
.head 6 -  Call SalTimerSet( pb1, 1, 1000 )
.head 6 -  Set bRelease = TRUE
.head 5 +  Else
.head 6 -  Call SalSetWindowText( pb1, 'Continuer' )
.head 6 +  If bHeure
.head 7 -  Set df2 = 'aura lieu le ' || SalFmtFormatDateTime( dt, 'dd/MM/yyyy' ) || ' à '  || SalFmtFormatDateTime( dt, 'hhh:mm' )
.head 6 +  Else
.head 7 -  Set df2 = 'aura lieu le ' || SalFmtFormatDateTime( dt, 'dd/MM/yyyy' )
.head 6 -  Set df3 =  "Vous ne pourrez pas utiliser les programmes de cette application lors de cette mise-à-jour"
.head 6 -  Set dt2 = dt - 1
.head 6 +  Select Case SalDateWeekday( dt2 )
.head 7 +  Case 0
.head 8 -  Set dt2  = dt2 - 1
.head 7 +  Case 6
.head 8 -  Set dt2  = dt2 - 1
.head 8 -  Break
.head 6 +  If ( ( SalDateCurrent(  ) - dt2 ) >= 0 ) and ( ( SalDateCurrent(  ) - dt2  ) < 1 )
.head 7 -  Set bRelease = TRUE
.head 6 +  ! Else
.head 7 -  Call SalEndDialog( hWndItem, TRUE )
.head 4 +  If not bRelease
.head 5 -  Call SalEndDialog( hWndItem, TRUE )
