.head 0 +  Application Description: SQLWindows version 5.0 starter application
.head 1 -  Outline Version - 4.0.31
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000CB0000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE9FFFFFF160000 0016000000850200 00E4010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600040003001B00 0200000057000000 0000F8287A170500 1D00FFFF4D61696E
0020: 0029000100040016 0000000000E91E80 0A00008600FFFF49 6E7465726E616C20
0040: 46756E6374696F6E 7300200001000400 150000000000E91E 800A0000DF00FFFF
0060: 5661726961626C65 73001E0001000400 690100000000F51E 100D0000F400FFFF
0080: 436C617373657300
.enddata
.data VIEWSIZE
0000: 8800
.enddata
.head 3 -  Left: -0.013"
.head 3 -  Top: 0.0"
.head 3 -  Width:  8.013"
.head 3 -  Height: 4.969"
.head 2 +  Options Box Location
.data VIEWINFO
0000: D4180909B80B1A00
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 4.15"
.head 3 -  Top: 1.885"
.head 3 -  Width:  3.8"
.head 3 -  Height: 2.073"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: 0.575"
.head 3 -  Top: 0.094"
.head 3 -  Width:  5.063"
.head 3 -  Height: 2.719"
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 6.4"
.head 3 -  Top: 0.729"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? Yes
.head 2 -  Enable Runtime Checks Of External References? Yes
.head 2 -  Use Release 4.0 Scope Rules? No
.head 1 +  Libraries
.head 2 -  File Include: VTSTR.APL
.head 2 -  File Include: steutl.apl
.head 2 -  File Include: DLLDPH1.APL
.head 2 -  File Include: sdklib.apl
.head 2 -  File Include: registry.apl
.head 2 -  File Include: cstste.apl
.head 2 -  File Include: cstwim.apl
.head 2 -  File Include: vtwin.apl
.head 2 -  File Include: vtmisc.apl
.head 2 -  File Include: cstructl.apl
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Line
.head 4 -  Line Color: Use Parent
.head 3 +  Frame
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0'%'
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;'($'###000')'
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 3 +  ! Library name: steutl.dll
.head 4 +  Function: DispatchMessageExcel
.head 5 -  Description: 
.head 5 -  Export Ordinal: 2
.head 5 -  Returns 
.head 5 -  Parameters 
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 4 -  !
.head 4 -  !
.head 4 -  ! COnstantes pour SYLK
.head 4 -  !
.head 4 -  Number: XLS_Bold			= 0x00002000
.head 4 -  Number: XLS_Italic			= 0x00004000
.head 4 -  Number: XLS_Underline		= 0x00008000
.head 4 -  !
.head 4 -  Number: XLS_Format		= 0x00001000
.head 4 -  !
.head 4 -  Number: XLS_Left			= 0x00010000
.head 4 -  Number: XLS_Center		= 0x00020000
.head 4 -  Number: XLS_Right			= 0x00040000
.head 4 -  Number: XLS_General		= 0x00080000
.head 4 -  !
.head 4 -  Number: XLS_StyleGeneral		= 0x00100000
.head 4 -  Number: XLS_StyleFixe		= 0x00200000
.head 4 -  Number: XLS_StyleScientific		= 0x00400000
.head 4 -  Number: XLS_StyleMoney		= 0x00800000
.head 4 -  !
.head 4 -  Number: XLS_BorderT		= 0x01000000
.head 4 -  Number: XLS_BorderB		= 0x02000000
.head 4 -  Number: XLS_BorderL		= 0x04000000
.head 4 -  Number: XLS_BorderR		= 0x08000000
.head 4 -  Number: XLS_Box			= XLS_BorderT | XLS_BorderL | XLS_BorderB | XLS_BorderR
.head 4 -  Number: XLS_Max			= 0xFFFFFFFF
.head 4 -  !
.head 3 +  User
.head 4 -  String: cSLKNull		= ''
.head 3 -  Enumerations
.head 2 -  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 4101553210
0000: 2A0000002A000000 0000000000000000 000002000E000204 0000000000000000
0020: 0000000000000000 1200020400000000 0000000000000000 00000000
.enddata
.head 2 +  Internal Functions
.head 3 +  Function: ExportTableur
.head 4 -  Description:
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  Window Handle: pwhTable
.head 5 -  String: psFileName
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  File Handle: fh
.head 5 -  Long String: ls
.head 5 -  Number: y
.head 5 -  Number: x
.head 5 -  Number: i
.head 5 -  String: s
.head 5 -  String: s1
.head 5 -  Window Handle: wh
.head 5 -  Number: wnRow
.head 5 -  Number: wnDataType
.head 4 +  Actions
.head 5 +  If SalFileOpen( fh, psFileName, OF_Create | OF_ReadWrite | OF_Text )
.head 6 -  Set ls = 'ID;PWXL;N;E
P;PGeneral
P;P0
P;P0.00
P;P#,##0
P;P#,##0.00
P;P#,##0\ _(0;;\-#,##0\ _(0
P;P#,##0\ _(0;;[Red]\-#,##0\ _(0
P;P#,##0.00\ _(0;;\-#,##0.00\ _(0
P;P#,##0.00\ _(0;;[Red]\-#,##0.00\ _(0
P;P#,##0\ "$";;\-#,##0\ "$"
P;P#,##0\ "$";;[Red]\-#,##0\ "$"
P;P#,##0.00\ "$";;\-#,##0.00\ "$"
P;P#,##0.00\ "$";;[Red]\-#,##0.00\ "$"
P;P0%
P;P0.00%
P;P0.00E+00
P;P##0.0E+0
P;P#\ ?/?
P;P#\ ??/??
P;Pd/mm/yy
P;Pd\-mmm\-yy
P;Pd\-mmm
P;Pmmm\-yy
P;Ph:mm\ AM/PM
P;Ph:mm:ss\ AM/PM
P;Ph:mm
P;Ph:mm:ss
P;Pd/mm/yy\ h:mm
P;Pmm:ss
P;Pmm:ss.0
P;P@
P;P[h]:mm:ss
P;P_-* #,##0\ "$"_-;;\-* #,##0\ "$"_-;;_-* "-"\ "$"_-;;_-@_-
P;P_-* #,##0\ _(0_-;;\-* #,##0\ _(0_-;;_-* "-"\ _(0_-;;_-@_-
P;P_-* #,##0.00\ "$"_-;;\-* #,##0.00\ "$"_-;;_-* "-"??\ "$"_-;;_-@_-
P;P_-* #,##0.00\ _(0_-;;\-* #,##0.00\ _(0_-;;_-* "-"??\ _(0_-;;_-@_-
P;FArial;M200
P;FArial;M200
P;FArial;M200
P;FArial;M200
P;EArial;M200
P;EArial;M200
P;EArial;M200
P;EArial;M200
P;EArial;M200;SB
F;P0;DG0G10;M255
B;Y1;X4;D0 0 254 1
O;D;V0;K47;G100 0.001
F;W1 256 11
'
.head 6 -  Call SalFileWrite( fh, ls, SalStrLength( ls ) )
.head 6 -  Set i = 1
.head 6 -  Set x = 1
.head 6 -  Set wh = SalGetFirstChild( pwhTable, TYPE_TableColumn )
.head 6 +  While wh != hWndNULL
.head 7 -  Set s = cSLKNull
.head 7 -  Call SalGetItemName( wh, s )
.head 7 -  Call SalTblGetColumnTitle( wh, s, 25 )
.head 7 +  If s!= '(untitled)'
.head 8 -  Set ls = 'F;P0;FG0C;SDM9;Y' || SalFmtFormatNumber( i, '0' ) || ';X' || SalFmtFormatNumber( x, '0' ) || '
'
.head 8 -  Set ls = ls || 'C;K"' || s || '"
'
.head 8 -  Call DispatchMessage()
.head 8 -  Call SalFileWrite( fh, ls, SalStrLength( ls ) )
.head 8 -  Set x = x + 1
.head 7 -  Set wh = SalGetNextChild( wh, TYPE_TableColumn )
.head 6 -  Set i = 2
.head 6 -  Set wnRow = TBL_MinRow
.head 6 +  While SalTblFindNextRow( pwhTable, wnRow, 0, 0 )
.head 7 -  Call SalTblSetContext( pwhTable, wnRow )
.head 7 -  Call SalTblSetFocusRow( pwhTable, wnRow )
.head 7 -  Set x = 1
.head 7 -  Set wh = SalGetFirstChild( pwhTable, TYPE_TableColumn )
.head 7 +  While wh != hWndNULL
.head 8 -  Set s = cSLKNull
.head 8 -  Call SalGetItemName( wh, s )
.head 8 -  Call SalTblGetColumnTitle( wh, s, 25 )
.head 8 +  If s!= '(untitled)'
.head 9 -  Call SalTblGetColumnText( pwhTable, SalTblQueryColumnID( wh ), s )
.head 9 -  Set wnDataType = SalGetDataType( wh )
.head 9 -  Set ls = 'F;P0;Y' || SalFmtFormatNumber( i, '0' ) || ';X' || SalFmtFormatNumber( x, '0' ) || '
'
.head 9 +  If wnDataType = DT_Number
.head 10 -  Set ls = ls || 'C;K' || s || '
'
.head 9 +  ! Else If wnDataType = DT_DateTime
.head 10 -  Set ls = ls || 'C;K' || s || '
'
.head 9 +  Else
.head 10 -  Set ls = ls || 'C;K"' || s || '"
'
.head 9 -  Call DispatchMessage( )
.head 9 -  Call SalFileWrite( fh, ls, SalStrLength( ls ) )
.head 9 -  Set x = x + 1
.head 8 -  Call DispatchMessage( )
.head 8 -  Set wh = SalGetNextChild( wh, TYPE_TableColumn )
.head 7 -  Set i = i + 1
.head 6 +  ! While SqlFetchNext( hSql, nRet )
.head 7 -  Set ls = 'C;Y' || SalFmtFormatNumber( i, '0' ) || ';X1;K"' || s1 || '"
C;X2;K"'
.head 7 -  Call DispatchMessage( )
.head 7 -  Set s = SalStrLeftX( s, 254 )
.head 7 -  Set s1 = SalStrRepeatX( ' ', SalStrLength( s ) * 4 )
.head 7 -  Call StrToSlk( s, s1 )
.head 7 -  Set ls = ls || s1 || '"
'
.head 7 -  Call SalFileWrite( fh, ls, SalStrLength( ls ) )
.head 7 -  Set i = i + 1
.head 6 -  Set ls = 'E
'
.head 6 -  Call SalFileWrite( fh, ls, SalStrLength( ls ) )
.head 6 -  Call SalFileClose( fh )
.head 3 +  Function: StrToSlk
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  String: si
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: so
.head 4 +  Actions
.head 5 -  Set so = SalStrRepeatX( ' ', SalStrLength( si ) * 4 )
.head 5 -  Call _StrToSlk( si, so )
.head 5 -  Return so
.head 3 +  Function: LoadExcel
.head 4 -  Description:
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  String: psFile
.head 4 -  Static Variables
.head 4 -  Local variables
.head 4 +  Actions
.head 5 -  Call WinExec( 'start ' || psFile, SW_HIDE )
.head 3 +  Function: RegistryReadStringFull
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Number:
.head 4 +  Parameters
.head 5 -  String: psAppl
.head 5 -  String: psKey
.head 5 -  String: psDefault
.head 5 -  Receive String: prsValue
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: lnKey
.head 5 -  Number: i
.head 5 -  String: s1
.head 5 -  String: s
.head 4 +  Actions
.head 5 -  Set s = psAppl
.head 5 +  While ( SalStrLength( s ) > 0 ) and SalStrLeftX( s, 1 ) = cRegBackSlash
.head 6 -  Set s = SalStrRightX( s, SalStrLength( s ) - 1 )
.head 5 +  While ( SalStrLength( s ) > 0 ) and SalStrRightX( s, 1 ) = cRegBackSlash
.head 6 -  Set s = SalStrLeftX( s, SalStrLength( s ) - 1 )
.head 5 -  Set s1 = s
.head 5 -  Set s = psKey
.head 5 +  While ( SalStrLength( s ) > 0 ) and SalStrLeftX( s, 1 ) = cRegBackSlash
.head 6 -  Set s = SalStrRightX( s, SalStrLength( s ) - 1 )
.head 5 +  While ( SalStrLength( s ) > 0 ) and SalStrRightX( s, 1 ) = cRegBackSlash
.head 6 -  Set s = SalStrLeftX( s, SalStrLength( s ) - 1 )
.head 5 -  Set s1 = s1 || cRegBackSlash || s
.head 5 -  Set s = s1
.head 5 +  While ( SalStrLength( s ) > 0 ) and SalStrLeftX( s, 1 ) = cRegBackSlash
.head 6 -  Set s = SalStrRightX( s, SalStrLength( s ) - 1 )
.head 5 +  While ( SalStrLength( s ) > 0 ) and SalStrRightX( s, 1 ) = cRegBackSlash
.head 6 -  Set s = SalStrLeftX( s, SalStrLength( s ) - 1 )
.head 5 -  Set s1 = s
.head 5 -  Set i = RegOpenKey( HKEY_LOCAL_MACHINE, s, lnKey )
.head 5 -  Set s = SalStrLeftX( psDefault || SalStrRepeatX( cRegSpace, 250 ), 250 )
.head 5 +  If i = 0
.head 6 -  ! Set s = SalStrRepeatX( ' ', 250 )
.head 6 -  Set i = SalStrLength( s )
.head 6 -  Set i = RegQueryKey( lnKey, cRegVide, s, i )
.head 5 -  Call RegCloseKey( lnKey )
.head 5 -  Set s = SalStrTrimX( s )
.head 5 -  Set prsValue = s
.head 5 -  Return i
.head 3 +  Function: GetFctSeparatorO
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 -  Parameters
.head 4 +  Static Variables
.head 5 -  String: ssSeparatorO
.head 4 +  Local variables
.head 5 -  String: sCls
.head 5 -  String: sAuxUserType
.head 4 +  Actions
.head 5 +  If ssSeparatorO = cSLKNull
.head 6 -  Set ssSeparatorO = '('
.head 6 -  Call RegistryReadStringFull( 'SoftWare\\CLASSES\\Excel.SLK', 'CLSID', cSLKNull, sCls )
.head 6 +  If sCls != cSLKNull
.head 7 -  Call RegistryReadStringFull( 'SoftWare\\CLASSES\\CLSID\\' || sCls || '\\AuxUserType', '3', cSLKNull, sAuxUserType )
.head 7 +  If sAuxUserType != cSLKNull
.head 8 -  Set sAuxUserType = SalStrRightX( sAuxUserType, SalStrLength( sAuxUserType ) - 16 )
.head 8 +  If sAuxUserType = '2000'
.head 9 -  Set ssSeparatorO = '['
.head 5 -  Return ssSeparatorO
.head 3 +  Function: GetFctSeparatorC
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 -  Parameters
.head 4 +  Static Variables
.head 5 -  String: ssSeparatorC
.head 4 +  Local variables
.head 5 -  String: sCls
.head 5 -  String: sAuxUserType
.head 4 +  Actions
.head 5 +  If ssSeparatorC = cSLKNull
.head 6 -  Set ssSeparatorC = ')'
.head 6 -  Call RegistryReadStringFull( 'SoftWare\\CLASSES\\Excel.SLK', 'CLSID', cSLKNull, sCls )
.head 6 +  If sCls != cSLKNull
.head 7 -  Call RegistryReadStringFull( 'SoftWare\\CLASSES\\CLSID\\' || sCls || '\\AuxUserType', '3', cSLKNull, sAuxUserType )
.head 7 +  If sAuxUserType != cSLKNull
.head 8 -  Set sAuxUserType = SalStrRightX( sAuxUserType, SalStrLength( sAuxUserType ) - 16 )
.head 8 +  If sAuxUserType = '2000'
.head 9 -  Set ssSeparatorC = ']'
.head 5 -  Return ssSeparatorC
.head 2 -  Named Menus
.head 2 +  Class Definitions
.head 3 +  Functional Class: TExcel
.head 4 -  Description:
.head 4 -  Derived From
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  Number: nNbrStyle
.head 4 +  Functions
.head 5 +  Function: __PalNumberToStrX
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  String:
.head 6 +  Parameters
.head 7 -  Number: pnNumber
.head 7 -  Number: pnNbrDec
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  String: s
.head 7 -  String: s1
.head 6 +  Actions
.head 7 -  Set s = SalNumberToStrX( pnNumber, pnNbrDec )
.head 7 -  Set s1 = VisStrSubstitute( s, ',', '.' )
.head 7 -  Return s1
.head 5 -  !
.head 5 +  Function: InitFile
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Long String: ls
.head 6 +  Actions
.head 7 -  Set ls = 'ID;PWXL;N;E
P;PGeneral
P;P0
P;P0.00
P;P#,##0
P;P#,##0.00
P;P#,##0\ _(0;;\-#,##0\ _(0
P;P#,##0\ _(0;;[Red]\-#,##0\ _(0
P;P#,##0.00\ _(0;;\-#,##0.00\ _(0
P;P#,##0.00\ _(0;;[Red]\-#,##0.00\ _(0
P;P#,##0\ "$";;\-#,##0\ "$"
P;P#,##0\ "$";;[Red]\-#,##0\ "$"
P;P#,##0.00\ "$";;\-#,##0.00\ "$"
P;P#,##0.00\ "$";;[Red]\-#,##0.00\ "$"
P;P0%
P;P0.00%
P;P0.00E+00
P;P##0.0E+0
P;P#\ ?/?
P;P#\ ??/??
P;Pd/mm/yy
P;Pd\-mmm\-yy
P;Pd\-mmm
P;Pmmm\-yy
P;Ph:mm\ AM/PM
P;Ph:mm:ss\ AM/PM
P;Ph:mm
P;Ph:mm:ss
P;Pd/mm/yy\ h:mm
P;Pmm:ss
P;Pmm:ss.0
P;P@
P;P[h]:mm:ss
P;P_-* #,##0\ "$"_-;;\-* #,##0\ "$"_-;;_-* "-"\ "$"_-;;_-@_-
P;P_-* #,##0\ _(0_-;;\-* #,##0\ _(0_-;;_-* "-"\ _(0_-;;_-@_-
P;P_-* #,##0.00\ "$"_-;;\-* #,##0.00\ "$"_-;;_-* "-"??\ "$"_-;;_-@_-
P;P_-* #,##0.00\ _(0_-;;\-* #,##0.00\ _(0_-;;_-* "-"??\ _(0_-;;_-@_-
P;FArial;M200
P;FArial;M200
P;FArial;M200
P;FArial;M200
P;EArial;M200
F;P0;DG0G10;M255
B;Y1;X4;D0 0 254 1
O;D;V0;K47;G100 0.001
F;W1 256 11
'
.head 7 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 7 -  !
.head 7 -  Set nNbrStyle = 5
.head 5 +  Function: TermFile
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Long String: ls
.head 6 +  Actions
.head 7 -  Set ls = 'E
'
.head 7 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 5 -  !
.head 5 +  Function: DefineStyle
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Number:
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 7 -  String: psPolice
.head 7 -  Number: pnTaille
.head 7 -  Number: pnAttr
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: i
.head 7 -  String: ls
.head 6 +  Actions
.head 7 -  Set nNbrStyle = nNbrStyle + 1
.head 7 -  Set i = nNbrStyle
.head 7 -  Set ls = cSLKNull
.head 7 +  If psPolice != cSLKNull
.head 8 -  Set ls = ls || ';E' || psPolice
.head 7 +  If pnTaille >= 0
.head 8 -  Set ls = ls || ';M' || SalNumberToStrX( pnTaille * 20, 0 )
.head 7 +  If pnAttr > 0
.head 8 -  Set ls = ls || ';S'
.head 8 +  If pnAttr & XLS_Bold
.head 9 -  Set ls = ls || 'B'
.head 8 +  If pnAttr & XLS_Italic
.head 9 -  Set ls = ls || 'I'
.head 8 +  If pnAttr & XLS_Underline
.head 9 -  Set ls = ls || 'U'
.head 7 +  If ls != cSLKNull
.head 8 -  Set ls = 'P' || ls || '
'
.head 8 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 8 -  Return i
.head 7 -  Return -1
.head 5 +  Function: HideRow
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 7 -  Number: pnLine
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: i
.head 7 -  String: ls
.head 6 +  Actions
.head 7 -  Set ls = cSLKNull
.head 7 +  If pnLine > 0
.head 8 -  Set ls = 'F;M0;R' || SalNumberToStrX( pnLine, 0 ) || '
'
.head 8 +  If ls != cSLKNull
.head 9 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 9 -  Return i
.head 5 +  Function: HideColumn
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 7 -  Number: pnCol
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: i
.head 7 -  String: ls
.head 6 +  Actions
.head 7 -  Set ls = cSLKNull
.head 7 +  If pnCol > 0
.head 8 -  Set ls = 'F;W' || SalNumberToStrX( pnCol, 0 ) || ' ' || SalNumberToStrX( pnCol, 0 ) || ' 0
'
.head 8 +  If ls != cSLKNull
.head 9 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 9 -  Return i
.head 5 +  Function: RowSize
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 7 -  Number: pnLine
.head 7 -  Number: pnSize
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: i
.head 7 -  String: ls
.head 6 +  Actions
.head 7 -  Set ls = cSLKNull
.head 7 +  If pnLine > 0
.head 8 -  Set ls = 'F;M' || SalNumberToStrX( pnSize * 20, 0 ) || ';R' || SalNumberToStrX( pnLine, 0 ) || '
'
.head 8 +  If ls != cSLKNull
.head 9 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 9 -  Return i
.head 5 +  Function: ColumnSize
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 7 -  Number: pnCol
.head 7 -  Number: pnSize
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: i
.head 7 -  String: ls
.head 6 +  Actions
.head 7 -  Set ls = cSLKNull
.head 7 +  If pnCol > 0
.head 8 -  Set ls = 'F;W' || SalNumberToStrX( pnCol, 0 ) || ' ' || SalNumberToStrX( pnCol, 0 ) || ' ' || SalNumberToStrX( pnSize, 0 ) || '
'
.head 8 +  If ls != cSLKNull
.head 9 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 9 -  Return i
.head 5 -  !
.head 5 +  Function: DefineCell
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 7 -  Number: py
.head 7 -  Number: px
.head 7 -  Number: pnStyle
.head 7 -  Number: pnAttr
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Long String: ls
.head 7 -  String: sStyle
.head 7 -  String: sAlign
.head 7 -  Number: n
.head 7 -  Number: n1
.head 6 +  Actions
.head 7 -  Set ls = cSLKNull
.head 7 +  If py > 0
.head 8 -  Set ls = ls || ';Y' || SalNumberToStrX( py, 0 )
.head 7 +  If px > 0
.head 8 -  Set ls = ls || ';X' || SalNumberToStrX( px, 0 )
.head 7 -  Set sStyle = cSLKNull
.head 7 +  If pnAttr > 0
.head 8 +  If pnAttr & XLS_BorderT
.head 9 -  Set sStyle = sStyle || 'T'
.head 8 +  If pnAttr & XLS_BorderB
.head 9 -  Set sStyle = sStyle || 'B'
.head 8 +  If pnAttr & XLS_BorderL
.head 9 -  Set sStyle = sStyle || 'L'
.head 8 +  If pnAttr & XLS_BorderR
.head 9 -  Set sStyle = sStyle || 'R'
.head 8 -  !
.head 8 -  Set sAlign = cSLKNull
.head 8 +  If pnAttr & XLS_StyleFixe
.head 9 -  Set sAlign = 'F'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleScientific
.head 9 -  Set sAlign = 'E'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleMoney
.head 9 -  Set sAlign = '$'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleGeneral
.head 9 -  Set sAlign = 'G0'
.head 8 +  If ( pnAttr & ( XLS_Left | XLS_Center | XLS_Right ) ) or ( sAlign != cSLKNull )
.head 9 +  If sAlign = cSLKNull
.head 10 -  Set sAlign = 'G0'
.head 9 +  If pnAttr & XLS_Left
.head 10 -  Set sAlign = sAlign || 'L'
.head 9 +  Else If pnAttr & XLS_Center
.head 10 -  Set sAlign = sAlign || 'C'
.head 9 +  Else If pnAttr & XLS_Right
.head 10 -  Set sAlign = sAlign || 'R'
.head 9 +  Else
.head 10 -  Set sAlign = sAlign || 'G'
.head 8 +  If sAlign != cSLKNull
.head 9 -  Set ls = ls || ';F' || sAlign
.head 7 +  If pnStyle > -1
.head 8 +  If sStyle = cSLKNull
.head 9 -  Set sStyle = 'D'
.head 8 -  Set sStyle = sStyle || 'M' || SalNumberToStrX( pnStyle, 0 )
.head 7 +  If sStyle != cSLKNull
.head 8 -  Set ls = ls || ';S' || sStyle
.head 8 +  If sAlign != cSLKNull
.head 9 -  Set ls = ls || sAlign
.head 7 +  If ls != cSLKNull
.head 8 +  If pnAttr & XLS_Format
.head 9 -  Set n1 = SalNumberMod( pnAttr, XLS_Format )
.head 9 -  Set n = SalNumberMod( n1, 10 )
.head 9 -  Set n = ( n1 - n ) / 10
.head 9 -  Set ls = ';P' || SalNumberToStrX( n, 0 ) || ls
.head 8 -  Set ls = 'F' || ls || '
'
.head 8 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 5 -  !
.head 5 +  Function: Write
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Long String: ls
.head 6 +  Actions
.head 7 -  Set ls = cSLKNull
.head 7 +  If ls != cSLKNull
.head 8 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 5 +  Function: WriteString
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 7 -  Number: py
.head 7 -  Number: px
.head 7 -  String: psValue
.head 7 -  Number: pnStyle
.head 7 -  Number: pnAttr
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Long String: ls
.head 7 -  String: sStyle
.head 7 -  String: sAlign
.head 7 -  Number: n
.head 7 -  Number: n1
.head 6 +  Actions
.head 7 -  Set ls = cSLKNull
.head 7 +  If py > 0
.head 8 -  Set ls = ls || ';Y' || SalNumberToStrX( py, 0 )
.head 7 +  If px > 0
.head 8 -  Set ls = ls || ';X' || SalNumberToStrX( px, 0 )
.head 7 -  Set sStyle = cSLKNull
.head 7 +  If pnAttr > 0
.head 8 +  If pnAttr & XLS_BorderT
.head 9 -  Set sStyle = sStyle || 'T'
.head 8 +  If pnAttr & XLS_BorderB
.head 9 -  Set sStyle = sStyle || 'B'
.head 8 +  If pnAttr & XLS_BorderL
.head 9 -  Set sStyle = sStyle || 'L'
.head 8 +  If pnAttr & XLS_BorderR
.head 9 -  Set sStyle = sStyle || 'R'
.head 8 -  !
.head 8 -  Set sAlign = cSLKNull
.head 8 +  If pnAttr & XLS_StyleFixe
.head 9 -  Set sAlign = 'F'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleScientific
.head 9 -  Set sAlign = 'E'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleMoney
.head 9 -  Set sAlign = '$'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleGeneral
.head 9 -  Set sAlign = 'G0'
.head 8 +  If ( pnAttr & ( XLS_Left | XLS_Center | XLS_Right ) ) or ( sAlign != cSLKNull )
.head 9 +  If sAlign = cSLKNull
.head 10 -  Set sAlign = 'G0'
.head 9 +  If pnAttr & XLS_Left
.head 10 -  Set sAlign = sAlign || 'L'
.head 9 +  Else If pnAttr & XLS_Center
.head 10 -  Set sAlign = sAlign || 'C'
.head 9 +  Else If pnAttr & XLS_Right
.head 10 -  Set sAlign = sAlign || 'R'
.head 9 +  Else
.head 10 -  Set sAlign = sAlign || 'G'
.head 8 +  If sAlign != cSLKNull
.head 9 -  Set ls = ls || ';F' || sAlign
.head 7 +  If pnStyle > -1
.head 8 +  If sStyle = cSLKNull
.head 9 -  Set sStyle = 'D'
.head 8 -  Set sStyle = sStyle || 'M' || SalNumberToStrX( pnStyle, 0 )
.head 7 +  If sStyle != cSLKNull
.head 8 -  Set ls = ls || ';S' || sStyle
.head 8 +  If sAlign != cSLKNull
.head 9 -  Set ls = ls || sAlign
.head 7 +  If ls != cSLKNull
.head 8 +  If pnAttr & XLS_Format
.head 9 -  Set n1 = SalNumberMod( pnAttr, XLS_Format )
.head 9 -  Set n = SalNumberMod( n1, 10 )
.head 9 -  Set n = ( n1 - n ) / 10
.head 9 -  Set ls = ';P' || SalNumberToStrX( n, 0 ) || ls
.head 8 -  Set ls = 'F' || ls || '
'
.head 8 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 7 -  Set ls = cSLKNull
.head 7 -  Set ls = 'C;K"' || StrToSlk( psValue ) || '"
'
.head 7 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 5 +  Function: WriteFormula
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 7 -  Number: py
.head 7 -  Number: px
.head 7 -  String: psValue
.head 7 -  Number: pnStyle
.head 7 -  Number: pnAttr
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Long String: ls
.head 7 -  String: sStyle
.head 7 -  String: sAlign
.head 7 -  Number: n
.head 7 -  Number: n1
.head 6 +  Actions
.head 7 -  Set ls = cSLKNull
.head 7 +  If py > 0
.head 8 -  Set ls = ls || ';Y' || SalNumberToStrX( py, 0 )
.head 7 +  If px > 0
.head 8 -  Set ls = ls || ';X' || SalNumberToStrX( px, 0 )
.head 7 -  Set sStyle = cSLKNull
.head 7 +  If pnAttr > 0
.head 8 +  If pnAttr & XLS_BorderT
.head 9 -  Set sStyle = sStyle || 'T'
.head 8 +  If pnAttr & XLS_BorderB
.head 9 -  Set sStyle = sStyle || 'B'
.head 8 +  If pnAttr & XLS_BorderL
.head 9 -  Set sStyle = sStyle || 'L'
.head 8 +  If pnAttr & XLS_BorderR
.head 9 -  Set sStyle = sStyle || 'R'
.head 8 -  !
.head 8 -  Set sAlign = cSLKNull
.head 8 +  If pnAttr & XLS_StyleFixe
.head 9 -  Set sAlign = 'F'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleScientific
.head 9 -  Set sAlign = 'E'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleMoney
.head 9 -  Set sAlign = '$'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleGeneral
.head 9 -  Set sAlign = 'G0'
.head 8 +  If ( pnAttr & ( XLS_Left | XLS_Center | XLS_Right ) ) or ( sAlign != cSLKNull )
.head 9 +  If sAlign = cSLKNull
.head 10 -  Set sAlign = 'G0'
.head 9 +  If pnAttr & XLS_Left
.head 10 -  Set sAlign = sAlign || 'L'
.head 9 +  Else If pnAttr & XLS_Center
.head 10 -  Set sAlign = sAlign || 'C'
.head 9 +  Else If pnAttr & XLS_Right
.head 10 -  Set sAlign = sAlign || 'R'
.head 9 +  Else
.head 10 -  Set sAlign = sAlign || 'G'
.head 8 +  If sAlign != cSLKNull
.head 9 -  Set ls = ls || ';F' || sAlign
.head 7 +  If pnStyle > -1
.head 8 +  If sStyle = cSLKNull
.head 9 -  Set sStyle = 'D'
.head 8 -  Set sStyle = sStyle || 'M' || SalNumberToStrX( pnStyle, 0 )
.head 7 +  If sStyle != cSLKNull
.head 8 -  Set ls = ls || ';S' || sStyle
.head 8 +  If sAlign != cSLKNull
.head 9 -  Set ls = ls || sAlign
.head 7 +  If ls != cSLKNull
.head 8 +  If pnAttr & XLS_Format
.head 9 -  Set n1 = SalNumberMod( pnAttr, XLS_Format )
.head 9 -  Set n = SalNumberMod( n1, 10 )
.head 9 -  Set n = ( n1 - n ) / 10
.head 9 -  Set ls = ';P' || SalNumberToStrX( n, 0 ) || ls
.head 8 -  Set ls = 'F' || ls || '
'
.head 8 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 7 -  Set ls = cSLKNull
.head 7 -  Set ls = 'C;E' || psValue || '
'
.head 7 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 5 +  Function: WriteNumber
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  File Handle: pfh
.head 7 -  Number: py
.head 7 -  Number: px
.head 7 -  Number: pnValue
.head 7 -  Number: pnDec
.head 7 -  Number: pnStyle
.head 7 -  Number: pnAttr
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Long String: ls
.head 7 -  String: sStyle
.head 7 -  String: sAlign
.head 7 -  Number: n
.head 7 -  Number: n1
.head 6 +  Actions
.head 7 -  Set ls = cSLKNull
.head 7 +  If py > 0
.head 8 -  Set ls = ls || ';Y' || SalNumberToStrX( py, 0 )
.head 7 +  If px > 0
.head 8 -  Set ls = ls || ';X' || SalNumberToStrX( px, 0 )
.head 7 -  Set sStyle = cSLKNull
.head 7 +  If pnAttr > 0
.head 8 +  If pnAttr & XLS_BorderT
.head 9 -  Set sStyle = sStyle || 'T'
.head 8 +  If pnAttr & XLS_BorderB
.head 9 -  Set sStyle = sStyle || 'B'
.head 8 +  If pnAttr & XLS_BorderL
.head 9 -  Set sStyle = sStyle || 'L'
.head 8 +  If pnAttr & XLS_BorderR
.head 9 -  Set sStyle = sStyle || 'R'
.head 8 -  !
.head 8 -  Set sAlign = cSLKNull
.head 8 +  If pnAttr & XLS_StyleFixe
.head 9 -  Set sAlign = 'F'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleScientific
.head 9 -  Set sAlign = 'E'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleMoney
.head 9 -  Set sAlign = '$'
.head 9 -  Set n = SalNumberMod( pnAttr, 10 )
.head 9 -  Set sAlign = sAlign || SalNumberToStrX( n, 0 )
.head 8 +  Else If pnAttr & XLS_StyleGeneral
.head 9 -  Set sAlign = 'G0'
.head 8 +  If ( pnAttr & ( XLS_Left | XLS_Center | XLS_Right ) ) or ( sAlign != cSLKNull )
.head 9 +  If sAlign = cSLKNull
.head 10 -  Set sAlign = 'G0'
.head 9 +  If pnAttr & XLS_Left
.head 10 -  Set sAlign = sAlign || 'L'
.head 9 +  Else If pnAttr & XLS_Center
.head 10 -  Set sAlign = sAlign || 'C'
.head 9 +  Else If pnAttr & XLS_Right
.head 10 -  Set sAlign = sAlign || 'R'
.head 9 +  Else
.head 10 -  Set sAlign = sAlign || 'G'
.head 8 +  If sAlign != cSLKNull
.head 9 -  Set ls = ls || ';F' || sAlign
.head 7 +  If pnStyle > -1
.head 8 +  If sStyle = cSLKNull
.head 9 -  Set sStyle = 'D'
.head 8 -  Set sStyle = sStyle || 'M' || SalNumberToStrX( pnStyle, 0 )
.head 7 +  If sStyle != cSLKNull
.head 8 -  Set ls = ls || ';S' || sStyle
.head 8 +  If sAlign != cSLKNull
.head 9 -  Set ls = ls || sAlign
.head 7 +  If ls != cSLKNull
.head 8 +  If pnAttr & XLS_Format
.head 9 -  Set n1 = SalNumberMod( pnAttr, XLS_Format )
.head 9 -  Set n = SalNumberMod( n1, 10 )
.head 9 -  Set n = ( n1 - n ) / 10
.head 9 -  Set ls = ';P' || SalNumberToStrX( n, 0 ) || ls
.head 8 -  Set ls = 'F' || ls || '
'
.head 8 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 7 -  Set ls = cSLKNull
.head 7 -  Set ls = 'C;K' || __PalNumberToStrX( pnValue, pnDec ) || '
'
.head 7 -  Call SalFileWrite( pfh, ls, SalStrLength( ls ) )
.head 2 +  Default Classes
.head 3 -  MDI Window: cBaseMDI
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field: cQuickMLField
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Option Button:
.head 3 -  ActiveX:
.head 3 -  Check Box:
.head 3 -  Child Table:
.head 3 -  Quest Child Window: cQuickDatabase
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture: cQuickPicture
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control: cQuickGraph
.head 2 -  Application Actions
