/* Filename        : CURDUORG.I                 */


/************************************************************************/
/*                                  */
/*    ON STATEMENTS                         */
/*                                  */
/************************************************************************/

ON CTRL-J      CURSOR-DOWN.
ON CTRL-K      CURSOR-UP.
ON CURSOR-DOWN CURSOR-DOWN.
ON CURSOR-UP   CURSOR-UP.
ON CTRL-BREAK  STOP.
