/**************************************************************************/
/*  Filename : PARTHEAD.I                                                 */
/**************************************************************************/

/* Progress BUG -> HEADER keep disapearing now and then ... */
PUT SCREEN ROW 6 COLUMN 15 mes1.
PUT SCREEN ROW 6 COLUMN 41 mes2.
PUT SCREEN ROW 6 COLUMN 62 mes3.

/**************************************************************************/
