/* Filename        : PMLPRTIN.I                 */

/************************************************************************/
/*                                  */
/*    SHARED VARIABLES                      */
/*                                  */
/************************************************************************/

DEFINE {1} SHARED VARIABLE partnr   AS INTEGER   FORMAT "99".
DEFINE {1} SHARED VARIABLE partnaam AS C FORMAT "x(18)". /* LIKE party.party_name. */
