//=======================================================================
/*

   File        : URNINT.H
   Creation    : 25/10/93

   Author      : B.S.S.

   Description : URNINT.CPP header file

*/
//=============================================================================
/*h*/

#ifndef _URNINT                       // avoid mutiple inclusions of this file
   #define _URNINT

//=========================== P R O T O T Y P E S =============================

int Control_Break( void);
void interrupt Keyboard_Handler(...);

#endif                                               // end of #ifndef _URNINT

//=== URNINT.H ================================================================
